// Code generated by Stan version 2.20.0

#include <stan/model/model_header.hpp>

namespace stan_qLearning_6params_peAN_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "C:/Users/cooper/Documents/gitHubRepositories/cooperAnalysis/matlabCode/operantMatching/learningModels/stan/bernoulli/stan_qLearning_6params_peAN.stan");
    reader.add_event(181, 179, "end", "C:/Users/cooper/Documents/gitHubRepositories/cooperAnalysis/matlabCode/operantMatching/learningModels/stan/bernoulli/stan_qLearning_6params_peAN.stan");
    return reader;
}

class stan_qLearning_6params_peAN_model
  : public stan::model::model_base_crtp<stan_qLearning_6params_peAN_model> {
private:
        int N;
        int T;
        std::vector<int> Tsesh;
        std::vector<std::vector<int> > choice;
        std::vector<std::vector<int> > outcome;
        vector_d initQ;
public:
    stan_qLearning_6params_peAN_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }

    stan_qLearning_6params_peAN_model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "stan_qLearning_6params_peAN_model_namespace::stan_qLearning_6params_peAN_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            // initialize data block variables from context__
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 1);

            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "T", "int", context__.to_vec());
            T = int(0);
            vals_i__ = context__.vals_i("T");
            pos__ = 0;
            T = vals_i__[pos__++];
            check_greater_or_equal(function__, "T", T, 1);

            current_statement_begin__ = 4;
            validate_non_negative_index("Tsesh", "N", N);
            context__.validate_dims("data initialization", "Tsesh", "int", context__.to_vec(N));
            Tsesh = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("Tsesh");
            pos__ = 0;
            size_t Tsesh_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < Tsesh_k_0_max__; ++k_0__) {
                Tsesh[k_0__] = vals_i__[pos__++];
            }
            size_t Tsesh_i_0_max__ = N;
            for (size_t i_0__ = 0; i_0__ < Tsesh_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Tsesh[i_0__]", Tsesh[i_0__], 1);
                check_less_or_equal(function__, "Tsesh[i_0__]", Tsesh[i_0__], T);
            }

            current_statement_begin__ = 5;
            validate_non_negative_index("choice", "N", N);
            validate_non_negative_index("choice", "T", T);
            context__.validate_dims("data initialization", "choice", "int", context__.to_vec(N,T));
            choice = std::vector<std::vector<int> >(N, std::vector<int>(T, int(0)));
            vals_i__ = context__.vals_i("choice");
            pos__ = 0;
            size_t choice_k_0_max__ = N;
            size_t choice_k_1_max__ = T;
            for (size_t k_1__ = 0; k_1__ < choice_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < choice_k_0_max__; ++k_0__) {
                    choice[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            size_t choice_i_0_max__ = N;
            size_t choice_i_1_max__ = T;
            for (size_t i_0__ = 0; i_0__ < choice_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < choice_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "choice[i_0__][i_1__]", choice[i_0__][i_1__], 0);
                    check_less_or_equal(function__, "choice[i_0__][i_1__]", choice[i_0__][i_1__], 2);
                }
            }

            current_statement_begin__ = 6;
            validate_non_negative_index("outcome", "N", N);
            validate_non_negative_index("outcome", "T", T);
            context__.validate_dims("data initialization", "outcome", "int", context__.to_vec(N,T));
            outcome = std::vector<std::vector<int> >(N, std::vector<int>(T, int(0)));
            vals_i__ = context__.vals_i("outcome");
            pos__ = 0;
            size_t outcome_k_0_max__ = N;
            size_t outcome_k_1_max__ = T;
            for (size_t k_1__ = 0; k_1__ < outcome_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < outcome_k_0_max__; ++k_0__) {
                    outcome[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            size_t outcome_i_0_max__ = N;
            size_t outcome_i_1_max__ = T;
            for (size_t i_0__ = 0; i_0__ < outcome_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < outcome_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "outcome[i_0__][i_1__]", outcome[i_0__][i_1__], 0);
                    check_less_or_equal(function__, "outcome[i_0__][i_1__]", outcome[i_0__][i_1__], 1);
                }
            }


            // initialize transformed data variables
            current_statement_begin__ = 9;
            validate_non_negative_index("initQ", "2", 2);
            initQ = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            stan::math::fill(initQ, DUMMY_VAR__);

            // execute transformed data statements
            current_statement_begin__ = 10;
            stan::math::assign(initQ, rep_vector(0.0, 2));

            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 15;
            validate_non_negative_index("mu_p", "6", 6);
            num_params_r__ += 6;
            current_statement_begin__ = 16;
            validate_non_negative_index("sigma", "6", 6);
            num_params_r__ += 6;
            current_statement_begin__ = 19;
            validate_non_negative_index("aNscale_pr", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 20;
            validate_non_negative_index("aNmin_pr", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 21;
            validate_non_negative_index("aP_pr", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 22;
            validate_non_negative_index("aF_pr", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 23;
            validate_non_negative_index("aPE_pr", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 24;
            validate_non_negative_index("beta_pr", "N", N);
            num_params_r__ += N;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~stan_qLearning_6params_peAN_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        current_statement_begin__ = 15;
        if (!(context__.contains_r("mu_p")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu_p missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu_p");
        pos__ = 0U;
        validate_non_negative_index("mu_p", "6", 6);
        context__.validate_dims("parameter initialization", "mu_p", "vector_d", context__.to_vec(6));
        Eigen::Matrix<double, Eigen::Dynamic, 1> mu_p(6);
        size_t mu_p_j_1_max__ = 6;
        for (size_t j_1__ = 0; j_1__ < mu_p_j_1_max__; ++j_1__) {
            mu_p(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(mu_p);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu_p: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 16;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        validate_non_negative_index("sigma", "6", 6);
        context__.validate_dims("parameter initialization", "sigma", "vector_d", context__.to_vec(6));
        Eigen::Matrix<double, Eigen::Dynamic, 1> sigma(6);
        size_t sigma_j_1_max__ = 6;
        for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
            sigma(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 19;
        if (!(context__.contains_r("aNscale_pr")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable aNscale_pr missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("aNscale_pr");
        pos__ = 0U;
        validate_non_negative_index("aNscale_pr", "N", N);
        context__.validate_dims("parameter initialization", "aNscale_pr", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> aNscale_pr(N);
        size_t aNscale_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aNscale_pr_j_1_max__; ++j_1__) {
            aNscale_pr(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(aNscale_pr);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aNscale_pr: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 20;
        if (!(context__.contains_r("aNmin_pr")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable aNmin_pr missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("aNmin_pr");
        pos__ = 0U;
        validate_non_negative_index("aNmin_pr", "N", N);
        context__.validate_dims("parameter initialization", "aNmin_pr", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> aNmin_pr(N);
        size_t aNmin_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aNmin_pr_j_1_max__; ++j_1__) {
            aNmin_pr(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(aNmin_pr);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aNmin_pr: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 21;
        if (!(context__.contains_r("aP_pr")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable aP_pr missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("aP_pr");
        pos__ = 0U;
        validate_non_negative_index("aP_pr", "N", N);
        context__.validate_dims("parameter initialization", "aP_pr", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> aP_pr(N);
        size_t aP_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aP_pr_j_1_max__; ++j_1__) {
            aP_pr(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(aP_pr);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aP_pr: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 22;
        if (!(context__.contains_r("aF_pr")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable aF_pr missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("aF_pr");
        pos__ = 0U;
        validate_non_negative_index("aF_pr", "N", N);
        context__.validate_dims("parameter initialization", "aF_pr", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> aF_pr(N);
        size_t aF_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aF_pr_j_1_max__; ++j_1__) {
            aF_pr(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(aF_pr);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aF_pr: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 23;
        if (!(context__.contains_r("aPE_pr")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable aPE_pr missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("aPE_pr");
        pos__ = 0U;
        validate_non_negative_index("aPE_pr", "N", N);
        context__.validate_dims("parameter initialization", "aPE_pr", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> aPE_pr(N);
        size_t aPE_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aPE_pr_j_1_max__; ++j_1__) {
            aPE_pr(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(aPE_pr);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aPE_pr: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 24;
        if (!(context__.contains_r("beta_pr")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_pr missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_pr");
        pos__ = 0U;
        validate_non_negative_index("beta_pr", "N", N);
        context__.validate_dims("parameter initialization", "beta_pr", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_pr(N);
        size_t beta_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < beta_pr_j_1_max__; ++j_1__) {
            beta_pr(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(beta_pr);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_pr: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);

            // model parameters
            current_statement_begin__ = 15;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> mu_p;
            (void) mu_p;  // dummy to suppress unused var warning
            if (jacobian__)
                mu_p = in__.vector_constrain(6, lp__);
            else
                mu_p = in__.vector_constrain(6);

            current_statement_begin__ = 16;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.vector_lb_constrain(0, 6, lp__);
            else
                sigma = in__.vector_lb_constrain(0, 6);

            current_statement_begin__ = 19;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aNscale_pr;
            (void) aNscale_pr;  // dummy to suppress unused var warning
            if (jacobian__)
                aNscale_pr = in__.vector_constrain(N, lp__);
            else
                aNscale_pr = in__.vector_constrain(N);

            current_statement_begin__ = 20;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aNmin_pr;
            (void) aNmin_pr;  // dummy to suppress unused var warning
            if (jacobian__)
                aNmin_pr = in__.vector_constrain(N, lp__);
            else
                aNmin_pr = in__.vector_constrain(N);

            current_statement_begin__ = 21;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aP_pr;
            (void) aP_pr;  // dummy to suppress unused var warning
            if (jacobian__)
                aP_pr = in__.vector_constrain(N, lp__);
            else
                aP_pr = in__.vector_constrain(N);

            current_statement_begin__ = 22;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aF_pr;
            (void) aF_pr;  // dummy to suppress unused var warning
            if (jacobian__)
                aF_pr = in__.vector_constrain(N, lp__);
            else
                aF_pr = in__.vector_constrain(N);

            current_statement_begin__ = 23;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aPE_pr;
            (void) aPE_pr;  // dummy to suppress unused var warning
            if (jacobian__)
                aPE_pr = in__.vector_constrain(N, lp__);
            else
                aPE_pr = in__.vector_constrain(N);

            current_statement_begin__ = 24;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_pr;
            (void) beta_pr;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_pr = in__.vector_constrain(N, lp__);
            else
                beta_pr = in__.vector_constrain(N);

            // transformed parameters
            current_statement_begin__ = 29;
            validate_non_negative_index("aNscale", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aNscale(N);
            stan::math::initialize(aNscale, DUMMY_VAR__);
            stan::math::fill(aNscale, DUMMY_VAR__);

            current_statement_begin__ = 30;
            validate_non_negative_index("aNmin", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aNmin(N);
            stan::math::initialize(aNmin, DUMMY_VAR__);
            stan::math::fill(aNmin, DUMMY_VAR__);

            current_statement_begin__ = 31;
            validate_non_negative_index("aP", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aP(N);
            stan::math::initialize(aP, DUMMY_VAR__);
            stan::math::fill(aP, DUMMY_VAR__);

            current_statement_begin__ = 32;
            validate_non_negative_index("aF", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aF(N);
            stan::math::initialize(aF, DUMMY_VAR__);
            stan::math::fill(aF, DUMMY_VAR__);

            current_statement_begin__ = 33;
            validate_non_negative_index("aPE", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aPE(N);
            stan::math::initialize(aPE, DUMMY_VAR__);
            stan::math::fill(aPE, DUMMY_VAR__);

            current_statement_begin__ = 34;
            validate_non_negative_index("beta", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta(N);
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);

            // transformed parameters block statements
            current_statement_begin__ = 36;
            for (int n = 1; n <= N; ++n) {

                current_statement_begin__ = 37;
                stan::model::assign(aNscale, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx((get_base1(mu_p, 1, "mu_p", 1) + (get_base1(sigma, 1, "sigma", 1) * get_base1(aNscale_pr, n, "aNscale_pr", 1)))), 
                            "assigning variable aNscale");
                current_statement_begin__ = 38;
                stan::model::assign(aNmin, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx((get_base1(mu_p, 2, "mu_p", 1) + (get_base1(sigma, 2, "sigma", 1) * get_base1(aNmin_pr, n, "aNmin_pr", 1)))), 
                            "assigning variable aNmin");
                current_statement_begin__ = 39;
                stan::model::assign(aP, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx((get_base1(mu_p, 3, "mu_p", 1) + (get_base1(sigma, 3, "sigma", 1) * get_base1(aP_pr, n, "aP_pr", 1)))), 
                            "assigning variable aP");
                current_statement_begin__ = 40;
                stan::model::assign(aF, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx((get_base1(mu_p, 4, "mu_p", 1) + (get_base1(sigma, 4, "sigma", 1) * get_base1(aF_pr, n, "aF_pr", 1)))), 
                            "assigning variable aF");
                current_statement_begin__ = 41;
                stan::model::assign(aPE, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx((get_base1(mu_p, 5, "mu_p", 1) + (get_base1(sigma, 5, "sigma", 1) * get_base1(aPE_pr, n, "aPE_pr", 1)))), 
                            "assigning variable aPE");
                current_statement_begin__ = 42;
                stan::model::assign(beta, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            (Phi_approx((get_base1(mu_p, 6, "mu_p", 1) + (get_base1(sigma, 6, "sigma", 1) * get_base1(beta_pr, n, "beta_pr", 1)))) * 10), 
                            "assigning variable beta");
            }

            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            current_statement_begin__ = 29;
            size_t aNscale_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aNscale_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(aNscale(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: aNscale" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable aNscale: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "aNscale", aNscale, 0);
            check_less_or_equal(function__, "aNscale", aNscale, 1);

            current_statement_begin__ = 30;
            size_t aNmin_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aNmin_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(aNmin(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: aNmin" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable aNmin: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "aNmin", aNmin, 0);
            check_less_or_equal(function__, "aNmin", aNmin, 1);

            current_statement_begin__ = 31;
            size_t aP_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aP_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(aP(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: aP" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable aP: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "aP", aP, 0);
            check_less_or_equal(function__, "aP", aP, 1);

            current_statement_begin__ = 32;
            size_t aF_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aF_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(aF(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: aF" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable aF: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "aF", aF, 0);
            check_less_or_equal(function__, "aF", aF, 1);

            current_statement_begin__ = 33;
            size_t aPE_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aPE_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(aPE(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: aPE" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable aPE: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "aPE", aPE, 0);
            check_less_or_equal(function__, "aPE", aPE, 1);

            current_statement_begin__ = 34;
            size_t beta_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(beta(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: beta" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "beta", beta, 0);
            check_less_or_equal(function__, "beta", beta, 10);


            // model body

            current_statement_begin__ = 47;
            lp_accum__.add(normal_log<propto__>(mu_p, 0, 1));
            current_statement_begin__ = 48;
            lp_accum__.add(cauchy_log<propto__>(sigma, 0, 1));
            current_statement_begin__ = 51;
            lp_accum__.add(normal_log<propto__>(aNscale_pr, 0, 1));
            current_statement_begin__ = 52;
            lp_accum__.add(normal_log<propto__>(aNmin_pr, 0, 1));
            current_statement_begin__ = 53;
            lp_accum__.add(normal_log<propto__>(aP_pr, 0, 1));
            current_statement_begin__ = 54;
            lp_accum__.add(normal_log<propto__>(aF_pr, 0, 1));
            current_statement_begin__ = 55;
            lp_accum__.add(normal_log<propto__>(aPE_pr, 0, 1));
            current_statement_begin__ = 56;
            lp_accum__.add(normal_log<propto__>(beta_pr, 0, 1));
            current_statement_begin__ = 59;
            for (int n = 1; n <= N; ++n) {
                {
                current_statement_begin__ = 60;
                validate_non_negative_index("Q", "2", 2);
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> Q(2);
                stan::math::initialize(Q, DUMMY_VAR__);
                stan::math::fill(Q, DUMMY_VAR__);

                current_statement_begin__ = 61;
                local_scalar_t__ PE(DUMMY_VAR__);
                (void) PE;  // dummy to suppress unused var warning
                stan::math::initialize(PE, DUMMY_VAR__);
                stan::math::fill(PE, DUMMY_VAR__);

                current_statement_begin__ = 62;
                local_scalar_t__ pePE(DUMMY_VAR__);
                (void) pePE;  // dummy to suppress unused var warning
                stan::math::initialize(pePE, DUMMY_VAR__);
                stan::math::fill(pePE, DUMMY_VAR__);

                current_statement_begin__ = 63;
                local_scalar_t__ peBar(DUMMY_VAR__);
                (void) peBar;  // dummy to suppress unused var warning
                stan::math::initialize(peBar, DUMMY_VAR__);
                stan::math::fill(peBar, DUMMY_VAR__);

                current_statement_begin__ = 64;
                local_scalar_t__ aN(DUMMY_VAR__);
                (void) aN;  // dummy to suppress unused var warning
                stan::math::initialize(aN, DUMMY_VAR__);
                stan::math::fill(aN, DUMMY_VAR__);

                current_statement_begin__ = 65;
                validate_non_negative_index("Qdiff", "get_base1(Tsesh, n, \"Tsesh\", 1)", get_base1(Tsesh, n, "Tsesh", 1));
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> Qdiff(get_base1(Tsesh, n, "Tsesh", 1));
                stan::math::initialize(Qdiff, DUMMY_VAR__);
                stan::math::fill(Qdiff, DUMMY_VAR__);


                current_statement_begin__ = 67;
                stan::math::assign(Q, initQ);
                current_statement_begin__ = 68;
                stan::math::assign(peBar, 0);
                current_statement_begin__ = 69;
                stan::math::assign(aN, get_base1(aNmin, n, "aNmin", 1));
                current_statement_begin__ = 71;
                for (int t = 1; t <= get_base1(Tsesh, n, "Tsesh", 1); ++t) {

                    current_statement_begin__ = 72;
                    stan::model::assign(Qdiff, 
                                stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list()), 
                                (get_base1(Q, 2, "Q", 1) - get_base1(Q, 1, "Q", 1)), 
                                "assigning variable Qdiff");
                    current_statement_begin__ = 73;
                    lp_accum__.add(bernoulli_logit_log<propto__>(get_base1(get_base1(choice, n, "choice", 1), t, "choice", 2), (get_base1(beta, n, "beta", 1) * get_base1(Qdiff, t, "Qdiff", 1))));
                    current_statement_begin__ = 75;
                    if (as_bool(logical_eq(get_base1(get_base1(choice, n, "choice", 1), t, "choice", 2), 1))) {

                        current_statement_begin__ = 76;
                        stan::math::assign(PE, (get_base1(get_base1(outcome, n, "outcome", 1), t, "outcome", 2) - get_base1(Q, 2, "Q", 1)));
                        current_statement_begin__ = 77;
                        stan::math::assign(pePE, (stan::math::fabs(PE) - peBar));
                        current_statement_begin__ = 78;
                        stan::math::assign(peBar, (peBar + (get_base1(aPE, n, "aPE", 1) * pePE)));
                        current_statement_begin__ = 79;
                        stan::math::assign(aN, ((peBar * get_base1(aNscale, n, "aNscale", 1)) + get_base1(aNmin, n, "aNmin", 1)));
                        current_statement_begin__ = 80;
                        if (as_bool(logical_lt(PE, 0))) {

                            current_statement_begin__ = 81;
                            stan::model::assign(Q, 
                                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                                        (stan::model::rvalue(Q, stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), "Q") + (aN * PE)), 
                                        "assigning variable Q");
                        } else {

                            current_statement_begin__ = 83;
                            stan::model::assign(Q, 
                                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                                        (stan::model::rvalue(Q, stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), "Q") + (get_base1(aP, n, "aP", 1) * PE)), 
                                        "assigning variable Q");
                        }
                        current_statement_begin__ = 85;
                        stan::model::assign(Q, 
                                    stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                                    (get_base1(Q, 1, "Q", 1) * get_base1(aF, n, "aF", 1)), 
                                    "assigning variable Q");
                    } else {

                        current_statement_begin__ = 87;
                        stan::math::assign(PE, (get_base1(get_base1(outcome, n, "outcome", 1), t, "outcome", 2) - get_base1(Q, 1, "Q", 1)));
                        current_statement_begin__ = 88;
                        stan::math::assign(pePE, (stan::math::fabs(PE) - peBar));
                        current_statement_begin__ = 89;
                        stan::math::assign(peBar, (peBar + (get_base1(aPE, n, "aPE", 1) * pePE)));
                        current_statement_begin__ = 90;
                        stan::math::assign(aN, ((peBar * get_base1(aNscale, n, "aNscale", 1)) + get_base1(aNmin, n, "aNmin", 1)));
                        current_statement_begin__ = 91;
                        if (as_bool(logical_lt(PE, 0))) {

                            current_statement_begin__ = 92;
                            stan::model::assign(Q, 
                                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                                        (stan::model::rvalue(Q, stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), "Q") + (aN * PE)), 
                                        "assigning variable Q");
                        } else {

                            current_statement_begin__ = 94;
                            stan::model::assign(Q, 
                                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                                        (stan::model::rvalue(Q, stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), "Q") + (get_base1(aP, n, "aP", 1) * PE)), 
                                        "assigning variable Q");
                        }
                        current_statement_begin__ = 96;
                        stan::model::assign(Q, 
                                    stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                                    (get_base1(Q, 2, "Q", 1) * get_base1(aF, n, "aF", 1)), 
                                    "assigning variable Q");
                    }
                }
                }
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("mu_p");
        names__.push_back("sigma");
        names__.push_back("aNscale_pr");
        names__.push_back("aNmin_pr");
        names__.push_back("aP_pr");
        names__.push_back("aF_pr");
        names__.push_back("aPE_pr");
        names__.push_back("beta_pr");
        names__.push_back("aNscale");
        names__.push_back("aNmin");
        names__.push_back("aP");
        names__.push_back("aF");
        names__.push_back("aPE");
        names__.push_back("beta");
        names__.push_back("mu_aNscale");
        names__.push_back("mu_aNmin");
        names__.push_back("mu_aP");
        names__.push_back("mu_aF");
        names__.push_back("mu_aPE");
        names__.push_back("mu_beta");
        names__.push_back("log_lik");
        names__.push_back("y_pred");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(6);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(6);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back(T);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "stan_qLearning_6params_peAN_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning

        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> mu_p = in__.vector_constrain(6);
        size_t mu_p_j_1_max__ = 6;
        for (size_t j_1__ = 0; j_1__ < mu_p_j_1_max__; ++j_1__) {
            vars__.push_back(mu_p(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> sigma = in__.vector_lb_constrain(0, 6);
        size_t sigma_j_1_max__ = 6;
        for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
            vars__.push_back(sigma(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> aNscale_pr = in__.vector_constrain(N);
        size_t aNscale_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aNscale_pr_j_1_max__; ++j_1__) {
            vars__.push_back(aNscale_pr(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> aNmin_pr = in__.vector_constrain(N);
        size_t aNmin_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aNmin_pr_j_1_max__; ++j_1__) {
            vars__.push_back(aNmin_pr(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> aP_pr = in__.vector_constrain(N);
        size_t aP_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aP_pr_j_1_max__; ++j_1__) {
            vars__.push_back(aP_pr(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> aF_pr = in__.vector_constrain(N);
        size_t aF_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aF_pr_j_1_max__; ++j_1__) {
            vars__.push_back(aF_pr(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> aPE_pr = in__.vector_constrain(N);
        size_t aPE_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aPE_pr_j_1_max__; ++j_1__) {
            vars__.push_back(aPE_pr(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_pr = in__.vector_constrain(N);
        size_t beta_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < beta_pr_j_1_max__; ++j_1__) {
            vars__.push_back(beta_pr(j_1__));
        }

        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        if (!include_tparams__ && !include_gqs__) return;

        try {
            // declare and define transformed parameters
            current_statement_begin__ = 29;
            validate_non_negative_index("aNscale", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> aNscale(N);
            stan::math::initialize(aNscale, DUMMY_VAR__);
            stan::math::fill(aNscale, DUMMY_VAR__);

            current_statement_begin__ = 30;
            validate_non_negative_index("aNmin", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> aNmin(N);
            stan::math::initialize(aNmin, DUMMY_VAR__);
            stan::math::fill(aNmin, DUMMY_VAR__);

            current_statement_begin__ = 31;
            validate_non_negative_index("aP", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> aP(N);
            stan::math::initialize(aP, DUMMY_VAR__);
            stan::math::fill(aP, DUMMY_VAR__);

            current_statement_begin__ = 32;
            validate_non_negative_index("aF", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> aF(N);
            stan::math::initialize(aF, DUMMY_VAR__);
            stan::math::fill(aF, DUMMY_VAR__);

            current_statement_begin__ = 33;
            validate_non_negative_index("aPE", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> aPE(N);
            stan::math::initialize(aPE, DUMMY_VAR__);
            stan::math::fill(aPE, DUMMY_VAR__);

            current_statement_begin__ = 34;
            validate_non_negative_index("beta", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> beta(N);
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);

            // do transformed parameters statements
            current_statement_begin__ = 36;
            for (int n = 1; n <= N; ++n) {

                current_statement_begin__ = 37;
                stan::model::assign(aNscale, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx((get_base1(mu_p, 1, "mu_p", 1) + (get_base1(sigma, 1, "sigma", 1) * get_base1(aNscale_pr, n, "aNscale_pr", 1)))), 
                            "assigning variable aNscale");
                current_statement_begin__ = 38;
                stan::model::assign(aNmin, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx((get_base1(mu_p, 2, "mu_p", 1) + (get_base1(sigma, 2, "sigma", 1) * get_base1(aNmin_pr, n, "aNmin_pr", 1)))), 
                            "assigning variable aNmin");
                current_statement_begin__ = 39;
                stan::model::assign(aP, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx((get_base1(mu_p, 3, "mu_p", 1) + (get_base1(sigma, 3, "sigma", 1) * get_base1(aP_pr, n, "aP_pr", 1)))), 
                            "assigning variable aP");
                current_statement_begin__ = 40;
                stan::model::assign(aF, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx((get_base1(mu_p, 4, "mu_p", 1) + (get_base1(sigma, 4, "sigma", 1) * get_base1(aF_pr, n, "aF_pr", 1)))), 
                            "assigning variable aF");
                current_statement_begin__ = 41;
                stan::model::assign(aPE, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx((get_base1(mu_p, 5, "mu_p", 1) + (get_base1(sigma, 5, "sigma", 1) * get_base1(aPE_pr, n, "aPE_pr", 1)))), 
                            "assigning variable aPE");
                current_statement_begin__ = 42;
                stan::model::assign(beta, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            (Phi_approx((get_base1(mu_p, 6, "mu_p", 1) + (get_base1(sigma, 6, "sigma", 1) * get_base1(beta_pr, n, "beta_pr", 1)))) * 10), 
                            "assigning variable beta");
            }

            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            current_statement_begin__ = 29;
            check_greater_or_equal(function__, "aNscale", aNscale, 0);
            check_less_or_equal(function__, "aNscale", aNscale, 1);

            current_statement_begin__ = 30;
            check_greater_or_equal(function__, "aNmin", aNmin, 0);
            check_less_or_equal(function__, "aNmin", aNmin, 1);

            current_statement_begin__ = 31;
            check_greater_or_equal(function__, "aP", aP, 0);
            check_less_or_equal(function__, "aP", aP, 1);

            current_statement_begin__ = 32;
            check_greater_or_equal(function__, "aF", aF, 0);
            check_less_or_equal(function__, "aF", aF, 1);

            current_statement_begin__ = 33;
            check_greater_or_equal(function__, "aPE", aPE, 0);
            check_less_or_equal(function__, "aPE", aPE, 1);

            current_statement_begin__ = 34;
            check_greater_or_equal(function__, "beta", beta, 0);
            check_less_or_equal(function__, "beta", beta, 10);

            // write transformed parameters
            if (include_tparams__) {
                size_t aNscale_j_1_max__ = N;
                for (size_t j_1__ = 0; j_1__ < aNscale_j_1_max__; ++j_1__) {
                    vars__.push_back(aNscale(j_1__));
                }
                size_t aNmin_j_1_max__ = N;
                for (size_t j_1__ = 0; j_1__ < aNmin_j_1_max__; ++j_1__) {
                    vars__.push_back(aNmin(j_1__));
                }
                size_t aP_j_1_max__ = N;
                for (size_t j_1__ = 0; j_1__ < aP_j_1_max__; ++j_1__) {
                    vars__.push_back(aP(j_1__));
                }
                size_t aF_j_1_max__ = N;
                for (size_t j_1__ = 0; j_1__ < aF_j_1_max__; ++j_1__) {
                    vars__.push_back(aF(j_1__));
                }
                size_t aPE_j_1_max__ = N;
                for (size_t j_1__ = 0; j_1__ < aPE_j_1_max__; ++j_1__) {
                    vars__.push_back(aPE(j_1__));
                }
                size_t beta_j_1_max__ = N;
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    vars__.push_back(beta(j_1__));
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 103;
            double mu_aNscale;
            (void) mu_aNscale;  // dummy to suppress unused var warning
            stan::math::initialize(mu_aNscale, DUMMY_VAR__);
            stan::math::fill(mu_aNscale, DUMMY_VAR__);

            current_statement_begin__ = 104;
            double mu_aNmin;
            (void) mu_aNmin;  // dummy to suppress unused var warning
            stan::math::initialize(mu_aNmin, DUMMY_VAR__);
            stan::math::fill(mu_aNmin, DUMMY_VAR__);

            current_statement_begin__ = 105;
            double mu_aP;
            (void) mu_aP;  // dummy to suppress unused var warning
            stan::math::initialize(mu_aP, DUMMY_VAR__);
            stan::math::fill(mu_aP, DUMMY_VAR__);

            current_statement_begin__ = 106;
            double mu_aF;
            (void) mu_aF;  // dummy to suppress unused var warning
            stan::math::initialize(mu_aF, DUMMY_VAR__);
            stan::math::fill(mu_aF, DUMMY_VAR__);

            current_statement_begin__ = 107;
            double mu_aPE;
            (void) mu_aPE;  // dummy to suppress unused var warning
            stan::math::initialize(mu_aPE, DUMMY_VAR__);
            stan::math::fill(mu_aPE, DUMMY_VAR__);

            current_statement_begin__ = 108;
            double mu_beta;
            (void) mu_beta;  // dummy to suppress unused var warning
            stan::math::initialize(mu_beta, DUMMY_VAR__);
            stan::math::fill(mu_beta, DUMMY_VAR__);

            current_statement_begin__ = 111;
            validate_non_negative_index("log_lik", "N", N);
            std::vector<double> log_lik(N, double(0));
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);

            current_statement_begin__ = 114;
            validate_non_negative_index("y_pred", "N", N);
            validate_non_negative_index("y_pred", "T", T);
            std::vector<std::vector<double> > y_pred(N, std::vector<double>(T, double(0)));
            stan::math::initialize(y_pred, DUMMY_VAR__);
            stan::math::fill(y_pred, DUMMY_VAR__);

            // generated quantities statements
            current_statement_begin__ = 117;
            for (int n = 1; n <= N; ++n) {

                current_statement_begin__ = 118;
                for (int t = 1; t <= T; ++t) {

                    current_statement_begin__ = 119;
                    stan::model::assign(y_pred, 
                                stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list())), 
                                -(1), 
                                "assigning variable y_pred");
                }
            }
            current_statement_begin__ = 123;
            stan::math::assign(mu_aNscale, Phi_approx(get_base1(mu_p, 1, "mu_p", 1)));
            current_statement_begin__ = 124;
            stan::math::assign(mu_aNmin, Phi_approx(get_base1(mu_p, 2, "mu_p", 1)));
            current_statement_begin__ = 125;
            stan::math::assign(mu_aP, Phi_approx(get_base1(mu_p, 3, "mu_p", 1)));
            current_statement_begin__ = 126;
            stan::math::assign(mu_aF, Phi_approx(get_base1(mu_p, 4, "mu_p", 1)));
            current_statement_begin__ = 127;
            stan::math::assign(mu_aPE, Phi_approx(get_base1(mu_p, 5, "mu_p", 1)));
            current_statement_begin__ = 128;
            stan::math::assign(mu_beta, (Phi_approx(get_base1(mu_p, 6, "mu_p", 1)) * 10));

            current_statement_begin__ = 131;
            for (int n = 1; n <= N; ++n) {
                {
                current_statement_begin__ = 132;
                validate_non_negative_index("Q", "2", 2);
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> Q(2);
                stan::math::initialize(Q, DUMMY_VAR__);
                stan::math::fill(Q, DUMMY_VAR__);

                current_statement_begin__ = 133;
                local_scalar_t__ PE(DUMMY_VAR__);
                (void) PE;  // dummy to suppress unused var warning
                stan::math::initialize(PE, DUMMY_VAR__);
                stan::math::fill(PE, DUMMY_VAR__);

                current_statement_begin__ = 134;
                local_scalar_t__ pePE(DUMMY_VAR__);
                (void) pePE;  // dummy to suppress unused var warning
                stan::math::initialize(pePE, DUMMY_VAR__);
                stan::math::fill(pePE, DUMMY_VAR__);

                current_statement_begin__ = 135;
                local_scalar_t__ peBar(DUMMY_VAR__);
                (void) peBar;  // dummy to suppress unused var warning
                stan::math::initialize(peBar, DUMMY_VAR__);
                stan::math::fill(peBar, DUMMY_VAR__);

                current_statement_begin__ = 136;
                local_scalar_t__ aN(DUMMY_VAR__);
                (void) aN;  // dummy to suppress unused var warning
                stan::math::initialize(aN, DUMMY_VAR__);
                stan::math::fill(aN, DUMMY_VAR__);

                current_statement_begin__ = 137;
                validate_non_negative_index("Qdiff", "get_base1(Tsesh, n, \"Tsesh\", 1)", get_base1(Tsesh, n, "Tsesh", 1));
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> Qdiff(get_base1(Tsesh, n, "Tsesh", 1));
                stan::math::initialize(Qdiff, DUMMY_VAR__);
                stan::math::fill(Qdiff, DUMMY_VAR__);


                current_statement_begin__ = 139;
                stan::math::assign(Q, initQ);
                current_statement_begin__ = 140;
                stan::math::assign(peBar, 0);
                current_statement_begin__ = 141;
                stan::math::assign(aN, get_base1(aNmin, n, "aNmin", 1));
                current_statement_begin__ = 143;
                stan::model::assign(log_lik, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable log_lik");
                current_statement_begin__ = 145;
                for (int t = 1; t <= get_base1(Tsesh, n, "Tsesh", 1); ++t) {

                    current_statement_begin__ = 146;
                    stan::model::assign(Qdiff, 
                                stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list()), 
                                (get_base1(Q, 2, "Q", 1) - get_base1(Q, 1, "Q", 1)), 
                                "assigning variable Qdiff");
                    current_statement_begin__ = 148;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                                (stan::model::rvalue(log_lik, stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), "log_lik") + bernoulli_logit_log(get_base1(get_base1(choice, n, "choice", 1), t, "choice", 2), (get_base1(beta, n, "beta", 1) * get_base1(Qdiff, t, "Qdiff", 1)))), 
                                "assigning variable log_lik");
                    current_statement_begin__ = 151;
                    stan::model::assign(y_pred, 
                                stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list())), 
                                categorical_rng(softmax(multiply(get_base1(beta, n, "beta", 1), Q)), base_rng__), 
                                "assigning variable y_pred");
                    current_statement_begin__ = 153;
                    if (as_bool(logical_eq(get_base1(get_base1(choice, n, "choice", 1), t, "choice", 2), 1))) {

                        current_statement_begin__ = 154;
                        stan::math::assign(PE, (get_base1(get_base1(outcome, n, "outcome", 1), t, "outcome", 2) - get_base1(Q, 2, "Q", 1)));
                        current_statement_begin__ = 155;
                        stan::math::assign(pePE, (stan::math::fabs(PE) - peBar));
                        current_statement_begin__ = 156;
                        stan::math::assign(peBar, (peBar + (get_base1(aPE, n, "aPE", 1) * pePE)));
                        current_statement_begin__ = 157;
                        stan::math::assign(aN, ((peBar * get_base1(aNscale, n, "aNscale", 1)) + get_base1(aNmin, n, "aNmin", 1)));
                        current_statement_begin__ = 158;
                        if (as_bool(logical_lt(PE, 0))) {

                            current_statement_begin__ = 159;
                            stan::model::assign(Q, 
                                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                                        (stan::model::rvalue(Q, stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), "Q") + (aN * PE)), 
                                        "assigning variable Q");
                        } else {

                            current_statement_begin__ = 161;
                            stan::model::assign(Q, 
                                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                                        (stan::model::rvalue(Q, stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), "Q") + (get_base1(aP, n, "aP", 1) * PE)), 
                                        "assigning variable Q");
                        }
                        current_statement_begin__ = 163;
                        stan::model::assign(Q, 
                                    stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                                    (get_base1(Q, 1, "Q", 1) * get_base1(aF, n, "aF", 1)), 
                                    "assigning variable Q");
                    } else {

                        current_statement_begin__ = 165;
                        stan::math::assign(PE, (get_base1(get_base1(outcome, n, "outcome", 1), t, "outcome", 2) - get_base1(Q, 1, "Q", 1)));
                        current_statement_begin__ = 166;
                        stan::math::assign(pePE, (stan::math::fabs(PE) - peBar));
                        current_statement_begin__ = 167;
                        stan::math::assign(peBar, (peBar + (get_base1(aPE, n, "aPE", 1) * pePE)));
                        current_statement_begin__ = 168;
                        stan::math::assign(aN, ((peBar * get_base1(aNscale, n, "aNscale", 1)) + get_base1(aNmin, n, "aNmin", 1)));
                        current_statement_begin__ = 169;
                        if (as_bool(logical_lt(PE, 0))) {

                            current_statement_begin__ = 170;
                            stan::model::assign(Q, 
                                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                                        (stan::model::rvalue(Q, stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), "Q") + (aN * PE)), 
                                        "assigning variable Q");
                        } else {

                            current_statement_begin__ = 172;
                            stan::model::assign(Q, 
                                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                                        (stan::model::rvalue(Q, stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), "Q") + (get_base1(aP, n, "aP", 1) * PE)), 
                                        "assigning variable Q");
                        }
                        current_statement_begin__ = 174;
                        stan::model::assign(Q, 
                                    stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                                    (get_base1(Q, 2, "Q", 1) * get_base1(aF, n, "aF", 1)), 
                                    "assigning variable Q");
                    }
                }
                }
            }

            // validate, write generated quantities
            current_statement_begin__ = 103;
            check_greater_or_equal(function__, "mu_aNscale", mu_aNscale, 0);
            check_less_or_equal(function__, "mu_aNscale", mu_aNscale, 1);

            vars__.push_back(mu_aNscale);

            current_statement_begin__ = 104;
            check_greater_or_equal(function__, "mu_aNmin", mu_aNmin, 0);
            check_less_or_equal(function__, "mu_aNmin", mu_aNmin, 1);

            vars__.push_back(mu_aNmin);

            current_statement_begin__ = 105;
            check_greater_or_equal(function__, "mu_aP", mu_aP, 0);
            check_less_or_equal(function__, "mu_aP", mu_aP, 1);

            vars__.push_back(mu_aP);

            current_statement_begin__ = 106;
            check_greater_or_equal(function__, "mu_aF", mu_aF, 0);
            check_less_or_equal(function__, "mu_aF", mu_aF, 1);

            vars__.push_back(mu_aF);

            current_statement_begin__ = 107;
            check_greater_or_equal(function__, "mu_aPE", mu_aPE, 0);
            check_less_or_equal(function__, "mu_aPE", mu_aPE, 1);

            vars__.push_back(mu_aPE);

            current_statement_begin__ = 108;
            check_greater_or_equal(function__, "mu_beta", mu_beta, 0);
            check_less_or_equal(function__, "mu_beta", mu_beta, 10);

            vars__.push_back(mu_beta);

            current_statement_begin__ = 111;
            size_t log_lik_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
                vars__.push_back(log_lik[k_0__]);
            }

            current_statement_begin__ = 114;
            size_t y_pred_k_0_max__ = N;
            size_t y_pred_k_1_max__ = T;
            for (size_t k_1__ = 0; k_1__ < y_pred_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < y_pred_k_0_max__; ++k_0__) {
                    vars__.push_back(y_pred[k_0__][k_1__]);
                }
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    std::string model_name() const {
        return "stan_qLearning_6params_peAN_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t mu_p_j_1_max__ = 6;
        for (size_t j_1__ = 0; j_1__ < mu_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma_j_1_max__ = 6;
        for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aNscale_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aNscale_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aNscale_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aNmin_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aNmin_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aNmin_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aP_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aP_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aP_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aF_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aF_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aF_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aPE_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aPE_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aPE_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < beta_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            size_t aNscale_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aNscale_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "aNscale" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t aNmin_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aNmin_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "aNmin" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t aP_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aP_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "aP" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t aF_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aF_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "aF" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t aPE_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aPE_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "aPE" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }

        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_aNscale";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_aNmin";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_aP";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_aF";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_aPE";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_beta";
        param_names__.push_back(param_name_stream__.str());
        size_t log_lik_k_0_max__ = N;
        for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t y_pred_k_0_max__ = N;
        size_t y_pred_k_1_max__ = T;
        for (size_t k_1__ = 0; k_1__ < y_pred_k_1_max__; ++k_1__) {
            for (size_t k_0__ = 0; k_0__ < y_pred_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "y_pred" << '.' << k_0__ + 1 << '.' << k_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t mu_p_j_1_max__ = 6;
        for (size_t j_1__ = 0; j_1__ < mu_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma_j_1_max__ = 6;
        for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aNscale_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aNscale_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aNscale_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aNmin_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aNmin_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aNmin_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aP_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aP_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aP_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aF_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aF_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aF_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aPE_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < aPE_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aPE_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < beta_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            size_t aNscale_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aNscale_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "aNscale" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t aNmin_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aNmin_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "aNmin" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t aP_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aP_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "aP" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t aF_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aF_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "aF" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t aPE_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < aPE_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "aPE" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }

        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_aNscale";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_aNmin";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_aP";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_aF";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_aPE";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_beta";
        param_names__.push_back(param_name_stream__.str());
        size_t log_lik_k_0_max__ = N;
        for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t y_pred_k_0_max__ = N;
        size_t y_pred_k_1_max__ = T;
        for (size_t k_1__ = 0; k_1__ < y_pred_k_1_max__; ++k_1__) {
            for (size_t k_0__ = 0; k_0__ < y_pred_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "y_pred" << '.' << k_0__ + 1 << '.' << k_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }

}; // model

}  // namespace

typedef stan_qLearning_6params_peAN_model_namespace::stan_qLearning_6params_peAN_model stan_model;

#ifndef USING_R

stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif

