
// Code generated by stanc f556d0df
#include <stan/model/model_header.hpp>
namespace stan_hmm_explore_model_namespace {

template <typename T, typename S>
std::vector<T> resize_to_match__(std::vector<T>& dst, const std::vector<S>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, -1>
resize_to_match__(Eigen::Matrix<T, -1, -1>& dst, const Eigen::Matrix<T, -1, -1>& src) {
  dst.resize(src.rows(), src.cols());
  return dst;
}

template <typename T>
Eigen::Matrix<T, 1, -1>
resize_to_match__(Eigen::Matrix<T, 1, -1>& dst, const Eigen::Matrix<T, 1, -1>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, 1>
resize_to_match__(Eigen::Matrix<T, -1, 1>& dst, const Eigen::Matrix<T, -1, 1>& src) {
  dst.resize(src.size());
  return dst;
}
std::vector<double> to_doubles__(std::initializer_list<double> x) {
  return x;
}

std::vector<stan::math::var> to_vars__(std::initializer_list<stan::math::var> x) {
  return x;
}

inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math; 

static int current_statement__ = 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 11, column 2 to column 17)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 12, column 2 to column 18)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 14, column 2 to column 18)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 15, column 2 to column 42)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 20, column 2 to column 16)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 21, column 2 to column 16)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 24, column 4 to column 21)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 23, column 16 to line 25, column 3)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 23, column 2 to line 25, column 3)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 28, column 4 to column 21)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 27, column 16 to line 29, column 3)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 27, column 2 to line 29, column 3)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 36, column 8 to column 28)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 37, column 8 to column 30)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 35, column 12 to line 38, column 7)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 34, column 8 to column 29)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 33, column 17 to line 35, column 7)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 33, column 6 to line 38, column 7)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 32, column 18 to line 39, column 5)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 32, column 4 to line 39, column 5)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 44, column 10 to column 33)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 43, column 11 to line 45, column 7)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 42, column 8 to column 29)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 41, column 19 to line 43, column 7)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 41, column 6 to line 45, column 7)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 40, column 18 to line 46, column 5)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 40, column 4 to line 46, column 5)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 31, column 16 to line 47, column 3)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 31, column 2 to line 47, column 3)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 51, column 2 to column 21)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 53, column 2 to column 23)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 55, column 4 to column 24)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 58, column 6 to column 51)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 57, column 18 to line 59, column 5)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 57, column 4 to line 59, column 5)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 66, column 10 to column 76)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 63, column 23 to line 67, column 9)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 63, column 8 to line 67, column 9)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 68, column 8 to column 50)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 62, column 21 to line 69, column 7)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 62, column 6 to line 69, column 7)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 61, column 19 to line 70, column 5)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 61, column 4 to line 70, column 5)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 72, column 2 to column 37)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 2, column 2 to column 17)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 3, column 2 to column 17)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 4, column 2 to column 17)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/hmm/stan_hmm_explore.stan', line 5, column 2 to column 11)"};



class stan_hmm_explore_model : public model_base_crtp<stan_hmm_explore_model> {

 private:
  int pos__;
  int T;
  int K;
  int N;
  std::vector<int> y;
 
 public:
  ~stan_hmm_explore_model() { }
  
  std::string model_name() const { return "stan_hmm_explore_model"; }
  
  stan_hmm_explore_model(stan::io::var_context& context__,
                         unsigned int random_seed__ = 0,
                         std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    typedef double local_scalar_t__;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "stan_hmm_explore_model_namespace::stan_hmm_explore_model";
    (void) function__;  // suppress unused var warning
    
    try {
      
      pos__ = 1;
      context__.validate_dims("data initialization","T","int",
          context__.to_vec());
      
      current_statement__ = 45;
      T = context__.vals_i("T")[(1 - 1)];
      context__.validate_dims("data initialization","K","int",
          context__.to_vec());
      
      current_statement__ = 46;
      K = context__.vals_i("K")[(1 - 1)];
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      
      current_statement__ = 47;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 48;
      validate_non_negative_index("y", "T", T);
      context__.validate_dims("data initialization","y","int",
          context__.to_vec(T));
      y = std::vector<int>(T, 0);
      
      current_statement__ = 48;
      assign(y, nil_index_list(), context__.vals_i("y"),
        "assigning variable y");
      current_statement__ = 45;
      current_statement__ = 45;
      check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 46;
      current_statement__ = 46;
      check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 47;
      current_statement__ = 47;
      check_greater_or_equal(function__, "N", N, 1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      current_statement__ = 1;
      validate_positive_index("pi1", "K", K);
      num_params_r__ += (K - 1);
      current_statement__ = 2;
      validate_positive_index("expP", "K", K);
      num_params_r__ += (K - 1);
      current_statement__ = 3;
      validate_positive_index("expO", "N", N);
      num_params_r__ += (N - 1);
      current_statement__ = 4;
      validate_non_negative_index("pStay", "(K - 1)", (K - 1));
      num_params_r__ += (K - 1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename T__>
  T__ log_prob(std::vector<T__>& params_r__, std::vector<int>& params_i__,
               std::ostream* pstream__ = 0) const {
    typedef T__ local_scalar_t__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "stan_hmm_explore_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    
    try {
      current_statement__ = 1;
      validate_positive_index("pi1", "K", K);
      Eigen::Matrix<local_scalar_t__, -1, 1> pi1;
      pi1 = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> pi1_in__;
      pi1_in__ = Eigen::Matrix<local_scalar_t__, -1, 1>((K - 1));
      
      current_statement__ = 1;
      pi1_in__ = in__.vector((K - 1));
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        assign(pi1, nil_index_list(),
          stan::math::simplex_constrain(pi1_in__, lp__),
          "assigning variable pi1");
      } else {
        current_statement__ = 1;
        assign(pi1, nil_index_list(),
          stan::math::simplex_constrain(pi1_in__), "assigning variable pi1");
      }
      current_statement__ = 2;
      validate_positive_index("expP", "K", K);
      Eigen::Matrix<local_scalar_t__, -1, 1> expP;
      expP = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> expP_in__;
      expP_in__ = Eigen::Matrix<local_scalar_t__, -1, 1>((K - 1));
      
      current_statement__ = 2;
      expP_in__ = in__.vector((K - 1));
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        assign(expP, nil_index_list(),
          stan::math::simplex_constrain(expP_in__, lp__),
          "assigning variable expP");
      } else {
        current_statement__ = 2;
        assign(expP, nil_index_list(),
          stan::math::simplex_constrain(expP_in__), "assigning variable expP");
      }
      current_statement__ = 3;
      validate_positive_index("expO", "N", N);
      Eigen::Matrix<local_scalar_t__, -1, 1> expO;
      expO = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> expO_in__;
      expO_in__ = Eigen::Matrix<local_scalar_t__, -1, 1>((N - 1));
      
      current_statement__ = 3;
      expO_in__ = in__.vector((N - 1));
      current_statement__ = 3;
      if (jacobian__) {
        current_statement__ = 3;
        assign(expO, nil_index_list(),
          stan::math::simplex_constrain(expO_in__, lp__),
          "assigning variable expO");
      } else {
        current_statement__ = 3;
        assign(expO, nil_index_list(),
          stan::math::simplex_constrain(expO_in__), "assigning variable expO");
      }
      current_statement__ = 4;
      validate_non_negative_index("pStay", "(K - 1)", (K - 1));
      Eigen::Matrix<local_scalar_t__, -1, 1> pStay;
      pStay = Eigen::Matrix<local_scalar_t__, -1, 1>((K - 1));
      
      current_statement__ = 4;
      pStay = in__.vector((K - 1));
      current_statement__ = 4;
      for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        current_statement__ = 4;
        if (jacobian__) {
          current_statement__ = 4;
          assign(pStay, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(pStay[(sym1__ - 1)], 0, 1, lp__),
            "assigning variable pStay");
        } else {
          current_statement__ = 4;
          assign(pStay, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(pStay[(sym1__ - 1)], 0, 1),
            "assigning variable pStay");
        }}
      current_statement__ = 5;
      validate_non_negative_index("A", "K", K);
      current_statement__ = 5;
      validate_non_negative_index("A", "K", K);
      Eigen::Matrix<local_scalar_t__, -1, -1> A;
      A = Eigen::Matrix<local_scalar_t__, -1, -1>(K, K);
      
      current_statement__ = 5;
      for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 5;
        for (size_t sym2__ = 1; sym2__ <= K; ++sym2__) {
          current_statement__ = 5;
          assign(A,
            cons_list(index_uni(sym1__),
              cons_list(index_uni(sym2__), nil_index_list())),
            std::numeric_limits<double>::quiet_NaN(), "assigning variable A");
        }}
      current_statement__ = 6;
      validate_non_negative_index("B", "K", K);
      current_statement__ = 6;
      validate_non_negative_index("B", "N", N);
      Eigen::Matrix<local_scalar_t__, -1, -1> B;
      B = Eigen::Matrix<local_scalar_t__, -1, -1>(K, N);
      
      current_statement__ = 6;
      for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 6;
        for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
          current_statement__ = 6;
          assign(B,
            cons_list(index_uni(sym1__),
              cons_list(index_uni(sym2__), nil_index_list())),
            std::numeric_limits<double>::quiet_NaN(), "assigning variable B");
        }}
      current_statement__ = 9;
      for (size_t i = 1; i <= K; ++i) {
        current_statement__ = 7;
        assign(A,
          cons_list(index_uni(1), cons_list(index_uni(i), nil_index_list())),
          expP[(i - 1)], "assigning variable A");}
      current_statement__ = 12;
      for (size_t i = 1; i <= N; ++i) {
        current_statement__ = 10;
        assign(B,
          cons_list(index_uni(1), cons_list(index_uni(i), nil_index_list())),
          expO[(i - 1)], "assigning variable B");}
      current_statement__ = 29;
      for (size_t i = 2; i <= K; ++i) {
        current_statement__ = 20;
        for (size_t j = 2; j <= K; ++j) {
          current_statement__ = 18;
          if (logical_neq(i, j)) {
            current_statement__ = 16;
            assign(A,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())), 0.000000001,
              "assigning variable A");
          } else {
            current_statement__ = 13;
            assign(A,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())),
              pStay[((i - 1) - 1)], "assigning variable A");
            current_statement__ = 14;
            assign(A,
              cons_list(index_uni(i),
                cons_list(index_uni(1), nil_index_list())),
              (1 - pStay[((i - 1) - 1)]), "assigning variable A");
          }}
        current_statement__ = 27;
        for (size_t j = 1; j <= N; ++j) {
          current_statement__ = 25;
          if (logical_neq(j, (i - 1))) {
            current_statement__ = 23;
            assign(B,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())), 0.000000001,
              "assigning variable B");
          } else {
            current_statement__ = 21;
            assign(B,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())),
              (1 - 0.000000001), "assigning variable B");
          }}}
      {
        current_statement__ = 30;
        lp_accum__.add(beta_log<propto__>(pStay, 8, 2));
        current_statement__ = 31;
        validate_non_negative_index("logalpha", "T", T);
        current_statement__ = 31;
        validate_non_negative_index("logalpha", "K", K);
        Eigen::Matrix<local_scalar_t__, -1, -1> logalpha;
        logalpha = Eigen::Matrix<local_scalar_t__, -1, -1>(T, K);
        
        current_statement__ = 31;
        for (size_t sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 31;
          for (size_t sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 31;
            assign(logalpha,
              cons_list(index_uni(sym1__),
                cons_list(index_uni(sym2__), nil_index_list())),
              std::numeric_limits<double>::quiet_NaN(),
              "assigning variable logalpha");}}
        current_statement__ = 32;
        validate_non_negative_index("accumulator", "K", K);
        std::vector<local_scalar_t__> accumulator;
        accumulator = std::vector<local_scalar_t__>(K, 0);
        
        current_statement__ = 35;
        for (size_t j = 1; j <= K; ++j) {
          current_statement__ = 33;
          assign(logalpha,
            cons_list(index_uni(1),
              cons_list(index_uni(j), nil_index_list())),
            (stan::math::log(pi1[(j - 1)]) +
              stan::math::log(
                rvalue(B,
                  cons_list(index_uni(j),
                    cons_list(index_uni(y[(1 - 1)]), nil_index_list())), "B"))),
            "assigning variable logalpha");}
        current_statement__ = 43;
        for (size_t t = 2; t <= T; ++t) {
          current_statement__ = 41;
          for (size_t j = 1; j <= K; ++j) {
            current_statement__ = 38;
            for (size_t i = 1; i <= K; ++i) {
              current_statement__ = 36;
              assign(accumulator, cons_list(index_uni(i), nil_index_list()),
                ((rvalue(logalpha,
                    cons_list(index_uni((t - 1)),
                      cons_list(index_uni(i), nil_index_list())), "logalpha")
                   +
                   stan::math::log(
                     rvalue(A,
                       cons_list(index_uni(i),
                         cons_list(index_uni(j), nil_index_list())), "A"))) +
                  stan::math::log(
                    rvalue(B,
                      cons_list(index_uni(j),
                        cons_list(index_uni(y[(t - 1)]), nil_index_list())),
                      "B"))), "assigning variable accumulator");}
            current_statement__ = 39;
            assign(logalpha,
              cons_list(index_uni(t),
                cons_list(index_uni(j), nil_index_list())),
              log_sum_exp(accumulator), "assigning variable logalpha");}}
        current_statement__ = 44;
        lp_accum__.add(
          log_sum_exp(
            rvalue(logalpha, cons_list(index_uni(T), nil_index_list()),
              "logalpha")));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob() 
    
  template <typename RNG>
  void write_array(RNG& base_rng__, std::vector<double>& params_r__,
                   std::vector<int>& params_i__, std::vector<double>& vars__,
                   bool emit_transformed_parameters__ = true,
                   bool emit_generated_quantities__ = true,
                   std::ostream* pstream__ = 0) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "stan_hmm_explore_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    
    try {
      current_statement__ = 1;
      validate_positive_index("pi1", "K", K);
      Eigen::Matrix<double, -1, 1> pi1;
      pi1 = Eigen::Matrix<double, -1, 1>(K);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> pi1_in__;
      pi1_in__ = Eigen::Matrix<local_scalar_t__, -1, 1>((K - 1));
      
      current_statement__ = 1;
      pi1_in__ = in__.vector((K - 1));
      current_statement__ = 1;
      assign(pi1, nil_index_list(), stan::math::simplex_constrain(pi1_in__),
        "assigning variable pi1");
      current_statement__ = 2;
      validate_positive_index("expP", "K", K);
      Eigen::Matrix<double, -1, 1> expP;
      expP = Eigen::Matrix<double, -1, 1>(K);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> expP_in__;
      expP_in__ = Eigen::Matrix<local_scalar_t__, -1, 1>((K - 1));
      
      current_statement__ = 2;
      expP_in__ = in__.vector((K - 1));
      current_statement__ = 2;
      assign(expP, nil_index_list(),
        stan::math::simplex_constrain(expP_in__), "assigning variable expP");
      current_statement__ = 3;
      validate_positive_index("expO", "N", N);
      Eigen::Matrix<double, -1, 1> expO;
      expO = Eigen::Matrix<double, -1, 1>(N);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> expO_in__;
      expO_in__ = Eigen::Matrix<local_scalar_t__, -1, 1>((N - 1));
      
      current_statement__ = 3;
      expO_in__ = in__.vector((N - 1));
      current_statement__ = 3;
      assign(expO, nil_index_list(),
        stan::math::simplex_constrain(expO_in__), "assigning variable expO");
      current_statement__ = 4;
      validate_non_negative_index("pStay", "(K - 1)", (K - 1));
      Eigen::Matrix<double, -1, 1> pStay;
      pStay = Eigen::Matrix<double, -1, 1>((K - 1));
      
      current_statement__ = 4;
      pStay = in__.vector((K - 1));
      current_statement__ = 4;
      for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        current_statement__ = 4;
        assign(pStay, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_constrain(pStay[(sym1__ - 1)], 0, 1),
          "assigning variable pStay");}
      current_statement__ = 5;
      validate_non_negative_index("A", "K", K);
      current_statement__ = 5;
      validate_non_negative_index("A", "K", K);
      Eigen::Matrix<double, -1, -1> A;
      A = Eigen::Matrix<double, -1, -1>(K, K);
      
      current_statement__ = 5;
      for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 5;
        for (size_t sym2__ = 1; sym2__ <= K; ++sym2__) {
          current_statement__ = 5;
          assign(A,
            cons_list(index_uni(sym1__),
              cons_list(index_uni(sym2__), nil_index_list())),
            std::numeric_limits<double>::quiet_NaN(), "assigning variable A");
        }}
      current_statement__ = 6;
      validate_non_negative_index("B", "K", K);
      current_statement__ = 6;
      validate_non_negative_index("B", "N", N);
      Eigen::Matrix<double, -1, -1> B;
      B = Eigen::Matrix<double, -1, -1>(K, N);
      
      current_statement__ = 6;
      for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 6;
        for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
          current_statement__ = 6;
          assign(B,
            cons_list(index_uni(sym1__),
              cons_list(index_uni(sym2__), nil_index_list())),
            std::numeric_limits<double>::quiet_NaN(), "assigning variable B");
        }}
      for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.push_back(pi1[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.push_back(expP[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(expO[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        vars__.push_back(pStay[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 9;
      for (size_t i = 1; i <= K; ++i) {
        current_statement__ = 7;
        assign(A,
          cons_list(index_uni(1), cons_list(index_uni(i), nil_index_list())),
          expP[(i - 1)], "assigning variable A");}
      current_statement__ = 12;
      for (size_t i = 1; i <= N; ++i) {
        current_statement__ = 10;
        assign(B,
          cons_list(index_uni(1), cons_list(index_uni(i), nil_index_list())),
          expO[(i - 1)], "assigning variable B");}
      current_statement__ = 29;
      for (size_t i = 2; i <= K; ++i) {
        current_statement__ = 20;
        for (size_t j = 2; j <= K; ++j) {
          current_statement__ = 18;
          if (logical_neq(i, j)) {
            current_statement__ = 16;
            assign(A,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())), 0.000000001,
              "assigning variable A");
          } else {
            current_statement__ = 13;
            assign(A,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())),
              pStay[((i - 1) - 1)], "assigning variable A");
            current_statement__ = 14;
            assign(A,
              cons_list(index_uni(i),
                cons_list(index_uni(1), nil_index_list())),
              (1 - pStay[((i - 1) - 1)]), "assigning variable A");
          }}
        current_statement__ = 27;
        for (size_t j = 1; j <= N; ++j) {
          current_statement__ = 25;
          if (logical_neq(j, (i - 1))) {
            current_statement__ = 23;
            assign(B,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())), 0.000000001,
              "assigning variable B");
          } else {
            current_statement__ = 21;
            assign(B,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())),
              (1 - 0.000000001), "assigning variable B");
          }}}
      for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (size_t sym2__ = 1; sym2__ <= K; ++sym2__) {
          vars__.push_back(
            rvalue(A,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "A"));}}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (size_t sym2__ = 1; sym2__ <= K; ++sym2__) {
          vars__.push_back(
            rvalue(B,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "B"));}}
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array() 
    
  void transform_inits(const stan::io::var_context& context__,
                       std::vector<int>& params_i__,
                       std::vector<double>& vars__, std::ostream* pstream__) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      
      pos__ = 1;
      current_statement__ = 1;
      validate_positive_index("pi1", "K", K);
      Eigen::Matrix<double, -1, 1> pi1;
      pi1 = Eigen::Matrix<double, -1, 1>(K);
      
      {
        std::vector<local_scalar_t__> pi1_flat__;
        current_statement__ = 1;
        assign(pi1_flat__, nil_index_list(), context__.vals_r("pi1"),
          "assigning variable pi1_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          assign(pi1, cons_list(index_uni(sym1__), nil_index_list()),
            pi1_flat__[(pos__ - 1)], "assigning variable pi1");
          current_statement__ = 1;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 1;
      assign(pi1, nil_index_list(), stan::math::simplex_free(pi1),
        "assigning variable pi1");
      current_statement__ = 2;
      validate_positive_index("expP", "K", K);
      Eigen::Matrix<double, -1, 1> expP;
      expP = Eigen::Matrix<double, -1, 1>(K);
      
      {
        std::vector<local_scalar_t__> expP_flat__;
        current_statement__ = 2;
        assign(expP_flat__, nil_index_list(), context__.vals_r("expP"),
          "assigning variable expP_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          assign(expP, cons_list(index_uni(sym1__), nil_index_list()),
            expP_flat__[(pos__ - 1)], "assigning variable expP");
          current_statement__ = 2;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 2;
      assign(expP, nil_index_list(), stan::math::simplex_free(expP),
        "assigning variable expP");
      current_statement__ = 3;
      validate_positive_index("expO", "N", N);
      Eigen::Matrix<double, -1, 1> expO;
      expO = Eigen::Matrix<double, -1, 1>(N);
      
      {
        std::vector<local_scalar_t__> expO_flat__;
        current_statement__ = 3;
        assign(expO_flat__, nil_index_list(), context__.vals_r("expO"),
          "assigning variable expO_flat__");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 3;
          assign(expO, cons_list(index_uni(sym1__), nil_index_list()),
            expO_flat__[(pos__ - 1)], "assigning variable expO");
          current_statement__ = 3;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 3;
      assign(expO, nil_index_list(), stan::math::simplex_free(expO),
        "assigning variable expO");
      current_statement__ = 4;
      validate_non_negative_index("pStay", "(K - 1)", (K - 1));
      Eigen::Matrix<double, -1, 1> pStay;
      pStay = Eigen::Matrix<double, -1, 1>((K - 1));
      
      {
        std::vector<local_scalar_t__> pStay_flat__;
        current_statement__ = 4;
        assign(pStay_flat__, nil_index_list(), context__.vals_r("pStay"),
          "assigning variable pStay_flat__");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
          current_statement__ = 4;
          assign(pStay, cons_list(index_uni(sym1__), nil_index_list()),
            pStay_flat__[(pos__ - 1)], "assigning variable pStay");
          current_statement__ = 4;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 4;
      for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        current_statement__ = 4;
        assign(pStay, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_free(pStay[(sym1__ - 1)], 0, 1),
          "assigning variable pStay");}
      for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        vars__.push_back(pi1[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        vars__.push_back(expP[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= (N - 1); ++sym1__) {
        vars__.push_back(expO[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        vars__.push_back(pStay[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits() 
    
  void get_param_names(std::vector<std::string>& names__) const {
    
    names__.resize(0);
    names__.push_back("pi1");
    names__.push_back("expP");
    names__.push_back("expO");
    names__.push_back("pStay");
    names__.push_back("A");
    names__.push_back("B");
    } // get_param_names() 
    
  void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.resize(0);
    std::vector<size_t> dims__;
    dims__.push_back(K);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(K);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back((K - 1));
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(K);
    
    dims__.push_back(K);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(K);
    
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    
    } // get_dims() 
    
  void constrained_param_names(std::vector<std::string>& param_names__,
                               bool emit_transformed_parameters__ = true,
                               bool emit_generated_quantities__ = true) const {
    
    for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.push_back(std::string() + "pi1" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.push_back(std::string() + "expP" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "expO" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      {
        param_names__.push_back(std::string() + "pStay" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          for (size_t sym2__ = 1; sym2__ <= K; ++sym2__) {
            {
              param_names__.push_back(std::string() + "A" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (size_t sym2__ = 1; sym2__ <= K; ++sym2__) {
            {
              param_names__.push_back(std::string() + "B" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  void unconstrained_param_names(std::vector<std::string>& param_names__,
                                 bool emit_transformed_parameters__ = true,
                                 bool emit_generated_quantities__ = true) const {
    
    for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      {
        param_names__.push_back(std::string() + "pi1" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      {
        param_names__.push_back(std::string() + "expP" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= (N - 1); ++sym1__) {
      {
        param_names__.push_back(std::string() + "expO" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      {
        param_names__.push_back(std::string() + "pStay" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      for (size_t sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          for (size_t sym2__ = 1; sym2__ <= K; ++sym2__) {
            {
              param_names__.push_back(std::string() + "A" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (size_t sym2__ = 1; sym2__ <= K; ++sym2__) {
            {
              param_names__.push_back(std::string() + "B" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"pi1\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"expP\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"expO\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"pStay\",\"type\":{\"name\":\"vector\",\"length\":" << (K - 1) << "},\"block\":\"parameters\"},{\"name\":\"A\",\"type\":{\"name\":\"matrix\",\"rows\":" << K << ",\"cols\":" << K << "},\"block\":\"transformed_parameters\"},{\"name\":\"B\",\"type\":{\"name\":\"matrix\",\"rows\":" << K << ",\"cols\":" << N << "},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"pi1\",\"type\":{\"name\":\"vector\",\"length\":" << (K - 1) << "},\"block\":\"parameters\"},{\"name\":\"expP\",\"type\":{\"name\":\"vector\",\"length\":" << (K - 1) << "},\"block\":\"parameters\"},{\"name\":\"expO\",\"type\":{\"name\":\"vector\",\"length\":" << (N - 1) << "},\"block\":\"parameters\"},{\"name\":\"pStay\",\"type\":{\"name\":\"vector\",\"length\":" << (K - 1) << "},\"block\":\"parameters\"},{\"name\":\"A\",\"type\":{\"name\":\"matrix\",\"rows\":" << K << ",\"cols\":" << K << "},\"block\":\"transformed_parameters\"},{\"name\":\"B\",\"type\":{\"name\":\"matrix\",\"rows\":" << K << ",\"cols\":" << N << "},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool emit_transformed_parameters__ = true,
                     bool emit_generated_quantities__ = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng__, params_r_vec, params_i_vec, vars_vec,
          emit_transformed_parameters__, emit_generated_quantities__, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    template <bool propto__, bool jacobian__, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto__,jacobian__,T_>(vec_params_r, vec_params_i, pstream);
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }

};
}
typedef stan_hmm_explore_model_namespace::stan_hmm_explore_model stan_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


