// Code generated by Stan version 2.20.0

#include <stan/model/model_header.hpp>

namespace stan_spikeRateMdl_v_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "C:/Users/cooper_PC/Desktop/githubRepositories/cooperAnalysis/matlabCode/operantMatching/functions/spikeAnalysis/spikeModels/stan_spikeRateMdl_v.stan");
    reader.add_event(57, 55, "end", "C:/Users/cooper_PC/Desktop/githubRepositories/cooperAnalysis/matlabCode/operantMatching/functions/spikeAnalysis/spikeModels/stan_spikeRateMdl_v.stan");
    return reader;
}

class stan_spikeRateMdl_v_model
  : public stan::model::model_base_crtp<stan_spikeRateMdl_v_model> {
private:
        int N;
        int T;
        std::vector<int> Tsesh;
        std::vector<std::vector<int> > outcome;
        std::vector<std::vector<double> > spikes;
public:
    stan_spikeRateMdl_v_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }

    stan_spikeRateMdl_v_model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "stan_spikeRateMdl_v_model_namespace::stan_spikeRateMdl_v_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            // initialize data block variables from context__
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 1);

            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "T", "int", context__.to_vec());
            T = int(0);
            vals_i__ = context__.vals_i("T");
            pos__ = 0;
            T = vals_i__[pos__++];
            check_greater_or_equal(function__, "T", T, 1);

            current_statement_begin__ = 4;
            validate_non_negative_index("Tsesh", "N", N);
            context__.validate_dims("data initialization", "Tsesh", "int", context__.to_vec(N));
            Tsesh = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("Tsesh");
            pos__ = 0;
            size_t Tsesh_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < Tsesh_k_0_max__; ++k_0__) {
                Tsesh[k_0__] = vals_i__[pos__++];
            }
            size_t Tsesh_i_0_max__ = N;
            for (size_t i_0__ = 0; i_0__ < Tsesh_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Tsesh[i_0__]", Tsesh[i_0__], 1);
                check_less_or_equal(function__, "Tsesh[i_0__]", Tsesh[i_0__], T);
            }

            current_statement_begin__ = 5;
            validate_non_negative_index("outcome", "N", N);
            validate_non_negative_index("outcome", "T", T);
            context__.validate_dims("data initialization", "outcome", "int", context__.to_vec(N,T));
            outcome = std::vector<std::vector<int> >(N, std::vector<int>(T, int(0)));
            vals_i__ = context__.vals_i("outcome");
            pos__ = 0;
            size_t outcome_k_0_max__ = N;
            size_t outcome_k_1_max__ = T;
            for (size_t k_1__ = 0; k_1__ < outcome_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < outcome_k_0_max__; ++k_0__) {
                    outcome[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            size_t outcome_i_0_max__ = N;
            size_t outcome_i_1_max__ = T;
            for (size_t i_0__ = 0; i_0__ < outcome_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < outcome_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "outcome[i_0__][i_1__]", outcome[i_0__][i_1__], 0);
                    check_less_or_equal(function__, "outcome[i_0__][i_1__]", outcome[i_0__][i_1__], 1);
                }
            }

            current_statement_begin__ = 6;
            validate_non_negative_index("spikes", "N", N);
            validate_non_negative_index("spikes", "T", T);
            context__.validate_dims("data initialization", "spikes", "double", context__.to_vec(N,T));
            spikes = std::vector<std::vector<double> >(N, std::vector<double>(T, double(0)));
            vals_r__ = context__.vals_r("spikes");
            pos__ = 0;
            size_t spikes_k_0_max__ = N;
            size_t spikes_k_1_max__ = T;
            for (size_t k_1__ = 0; k_1__ < spikes_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < spikes_k_0_max__; ++k_0__) {
                    spikes[k_0__][k_1__] = vals_r__[pos__++];
                }
            }


            // initialize transformed data variables
            // execute transformed data statements

            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 10;
            validate_non_negative_index("v_pr", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 11;
            validate_non_negative_index("slope", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 12;
            validate_non_negative_index("intercept", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 13;
            validate_non_negative_index("sigma", "N", N);
            num_params_r__ += N;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~stan_spikeRateMdl_v_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        current_statement_begin__ = 10;
        if (!(context__.contains_r("v_pr")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable v_pr missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("v_pr");
        pos__ = 0U;
        validate_non_negative_index("v_pr", "N", N);
        context__.validate_dims("parameter initialization", "v_pr", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> v_pr(N);
        size_t v_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < v_pr_j_1_max__; ++j_1__) {
            v_pr(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(v_pr);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable v_pr: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 11;
        if (!(context__.contains_r("slope")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable slope missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("slope");
        pos__ = 0U;
        validate_non_negative_index("slope", "N", N);
        context__.validate_dims("parameter initialization", "slope", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> slope(N);
        size_t slope_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < slope_j_1_max__; ++j_1__) {
            slope(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(slope);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable slope: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 12;
        if (!(context__.contains_r("intercept")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable intercept missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("intercept");
        pos__ = 0U;
        validate_non_negative_index("intercept", "N", N);
        context__.validate_dims("parameter initialization", "intercept", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> intercept(N);
        size_t intercept_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < intercept_j_1_max__; ++j_1__) {
            intercept(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(intercept);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable intercept: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 13;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        validate_non_negative_index("sigma", "N", N);
        context__.validate_dims("parameter initialization", "sigma", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> sigma(N);
        size_t sigma_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
            sigma(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);

            // model parameters
            current_statement_begin__ = 10;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> v_pr;
            (void) v_pr;  // dummy to suppress unused var warning
            if (jacobian__)
                v_pr = in__.vector_constrain(N, lp__);
            else
                v_pr = in__.vector_constrain(N);

            current_statement_begin__ = 11;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> slope;
            (void) slope;  // dummy to suppress unused var warning
            if (jacobian__)
                slope = in__.vector_constrain(N, lp__);
            else
                slope = in__.vector_constrain(N);

            current_statement_begin__ = 12;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> intercept;
            (void) intercept;  // dummy to suppress unused var warning
            if (jacobian__)
                intercept = in__.vector_constrain(N, lp__);
            else
                intercept = in__.vector_constrain(N);

            current_statement_begin__ = 13;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.vector_lb_constrain(0, N, lp__);
            else
                sigma = in__.vector_lb_constrain(0, N);

            // transformed parameters
            current_statement_begin__ = 17;
            validate_non_negative_index("v", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> v(N);
            stan::math::initialize(v, DUMMY_VAR__);
            stan::math::fill(v, DUMMY_VAR__);

            // transformed parameters block statements
            current_statement_begin__ = 20;
            for (int n = 1; n <= N; ++n) {

                current_statement_begin__ = 21;
                stan::model::assign(v, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx(get_base1(v_pr, n, "v_pr", 1)), 
                            "assigning variable v");
            }

            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            current_statement_begin__ = 17;
            size_t v_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < v_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(v(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: v" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable v: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "v", v, 0);
            check_less_or_equal(function__, "v", v, 1);


            // model body

            current_statement_begin__ = 25;
            lp_accum__.add(normal_log<propto__>(v_pr, 0, 1));
            current_statement_begin__ = 26;
            lp_accum__.add(normal_log<propto__>(slope, 0, 10));
            current_statement_begin__ = 27;
            lp_accum__.add(normal_log<propto__>(intercept, 0, 10));
            current_statement_begin__ = 28;
            lp_accum__.add(cauchy_log<propto__>(sigma, 0, 5));
            current_statement_begin__ = 31;
            for (int n = 1; n <= N; ++n) {
                {
                current_statement_begin__ = 32;
                validate_non_negative_index("R", "get_base1(Tsesh, n, \"Tsesh\", 1)", get_base1(Tsesh, n, "Tsesh", 1));
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> R(get_base1(Tsesh, n, "Tsesh", 1));
                stan::math::initialize(R, DUMMY_VAR__);
                stan::math::fill(R, DUMMY_VAR__);


                current_statement_begin__ = 33;
                stan::model::assign(R, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable R");
                current_statement_begin__ = 35;
                for (int t = 1; t <= (get_base1(Tsesh, n, "Tsesh", 1) - 1); ++t) {

                    current_statement_begin__ = 36;
                    stan::model::assign(R, 
                                stan::model::cons_list(stan::model::index_uni((t + 1)), stan::model::nil_index_list()), 
                                ((get_base1(v, n, "v", 1) * get_base1(get_base1(outcome, n, "outcome", 1), t, "outcome", 2)) + ((1 - get_base1(v, n, "v", 1)) * get_base1(R, t, "R", 1))), 
                                "assigning variable R");
                }
                current_statement_begin__ = 38;
                lp_accum__.add(normal_log<propto__>(stan::model::rvalue(spikes, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_min_max(1, get_base1(Tsesh, n, "Tsesh", 1)), stan::model::nil_index_list())), "spikes"), add(multiply(get_base1(slope, n, "slope", 1), R), get_base1(intercept, n, "intercept", 1)), get_base1(sigma, n, "sigma", 1)));
                }
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("v_pr");
        names__.push_back("slope");
        names__.push_back("intercept");
        names__.push_back("sigma");
        names__.push_back("v");
        names__.push_back("R");
        names__.push_back("spikes_pred");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back(T);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back(T);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "stan_spikeRateMdl_v_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning

        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> v_pr = in__.vector_constrain(N);
        size_t v_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < v_pr_j_1_max__; ++j_1__) {
            vars__.push_back(v_pr(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> slope = in__.vector_constrain(N);
        size_t slope_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < slope_j_1_max__; ++j_1__) {
            vars__.push_back(slope(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> intercept = in__.vector_constrain(N);
        size_t intercept_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < intercept_j_1_max__; ++j_1__) {
            vars__.push_back(intercept(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> sigma = in__.vector_lb_constrain(0, N);
        size_t sigma_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
            vars__.push_back(sigma(j_1__));
        }

        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        if (!include_tparams__ && !include_gqs__) return;

        try {
            // declare and define transformed parameters
            current_statement_begin__ = 17;
            validate_non_negative_index("v", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> v(N);
            stan::math::initialize(v, DUMMY_VAR__);
            stan::math::fill(v, DUMMY_VAR__);

            // do transformed parameters statements
            current_statement_begin__ = 20;
            for (int n = 1; n <= N; ++n) {

                current_statement_begin__ = 21;
                stan::model::assign(v, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            Phi_approx(get_base1(v_pr, n, "v_pr", 1)), 
                            "assigning variable v");
            }

            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            current_statement_begin__ = 17;
            check_greater_or_equal(function__, "v", v, 0);
            check_less_or_equal(function__, "v", v, 1);

            // write transformed parameters
            if (include_tparams__) {
                size_t v_j_1_max__ = N;
                for (size_t j_1__ = 0; j_1__ < v_j_1_max__; ++j_1__) {
                    vars__.push_back(v(j_1__));
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 43;
            validate_non_negative_index("R", "N", N);
            validate_non_negative_index("R", "T", T);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> R(N, T);
            stan::math::initialize(R, DUMMY_VAR__);
            stan::math::fill(R, DUMMY_VAR__);

            current_statement_begin__ = 44;
            validate_non_negative_index("spikes_pred", "N", N);
            validate_non_negative_index("spikes_pred", "T", T);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> spikes_pred(N, T);
            stan::math::initialize(spikes_pred, DUMMY_VAR__);
            stan::math::fill(spikes_pred, DUMMY_VAR__);

            // generated quantities statements
            current_statement_begin__ = 46;
            for (int n = 1; n <= N; ++n) {

                current_statement_begin__ = 47;
                stan::model::assign(R, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                            0, 
                            "assigning variable R");
                current_statement_begin__ = 49;
                for (int t = 1; t <= (get_base1(Tsesh, n, "Tsesh", 1) - 1); ++t) {

                    current_statement_begin__ = 50;
                    stan::model::assign(R, 
                                stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_uni((t + 1)), stan::model::nil_index_list())), 
                                ((get_base1(v, n, "v", 1) * get_base1(get_base1(outcome, n, "outcome", 1), t, "outcome", 2)) + ((1 - get_base1(v, n, "v", 1)) * get_base1(R, n, t, "R", 1))), 
                                "assigning variable R");
                }
                current_statement_begin__ = 53;
                stan::model::assign(spikes_pred, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_min_max(1, get_base1(Tsesh, n, "Tsesh", 1)), stan::model::nil_index_list())), 
                            add(multiply(get_base1(slope, n, "slope", 1), stan::model::rvalue(R, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_min_max(1, get_base1(Tsesh, n, "Tsesh", 1)), stan::model::nil_index_list())), "R")), get_base1(intercept, n, "intercept", 1)), 
                            "assigning variable spikes_pred");
            }

            // validate, write generated quantities
            current_statement_begin__ = 43;
            size_t R_j_2_max__ = T;
            size_t R_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < R_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                    vars__.push_back(R(j_1__, j_2__));
                }
            }

            current_statement_begin__ = 44;
            size_t spikes_pred_j_2_max__ = T;
            size_t spikes_pred_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < spikes_pred_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < spikes_pred_j_1_max__; ++j_1__) {
                    vars__.push_back(spikes_pred(j_1__, j_2__));
                }
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    std::string model_name() const {
        return "stan_spikeRateMdl_v_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t v_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < v_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "v_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t slope_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < slope_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "slope" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t intercept_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < intercept_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "intercept" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            size_t v_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < v_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "v" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }

        if (!include_gqs__) return;
        size_t R_j_2_max__ = T;
        size_t R_j_1_max__ = N;
        for (size_t j_2__ = 0; j_2__ < R_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "R" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t spikes_pred_j_2_max__ = T;
        size_t spikes_pred_j_1_max__ = N;
        for (size_t j_2__ = 0; j_2__ < spikes_pred_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < spikes_pred_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "spikes_pred" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t v_pr_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < v_pr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "v_pr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t slope_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < slope_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "slope" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t intercept_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < intercept_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "intercept" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            size_t v_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < v_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "v" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }

        if (!include_gqs__) return;
        size_t R_j_2_max__ = T;
        size_t R_j_1_max__ = N;
        for (size_t j_2__ = 0; j_2__ < R_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "R" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t spikes_pred_j_2_max__ = T;
        size_t spikes_pred_j_1_max__ = N;
        for (size_t j_2__ = 0; j_2__ < spikes_pred_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < spikes_pred_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "spikes_pred" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }

}; // model

}  // namespace

typedef stan_spikeRateMdl_v_model_namespace::stan_spikeRateMdl_v_model stan_model;

#ifndef USING_R

stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif

