function [fit] = runStanModel(modelName, filePath, session_dat, iter, warmup, savePath)

switch modelName
    case 'twoParam'
        fit = stan('file',[filePath 'stan_qLearning_2params.stan'],'data',session_dat,'verbose',true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'threeParam'
        fit = stan('file',[filePath 'stan_qLearning_3params.stan'],'data',session_dat,'verbose',true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fourParam'
        fit = stan('file',[filePath 'stan_qLearning_4params.stan'],'data',session_dat,'verbose',true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fourParam_tF'
        fit = stan('file',[filePath 'stan_qLearning_4params_tF.stan'],'data',session_dat,'verbose',true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fourParam_tF_oneside'
        fit = stan('file',[filePath 'stan_qLearning_4params_tF_oneside.stan'],'data',session_dat,'verbose',true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
   case 'fourParam_manSoft'
        fit = stan('file',[filePath 'stan_qLearning_4params_manSoft.stan'],'data',session_dat,'verbose',true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fiveParam_k'
        fit = stan('file',[filePath 'stan_qLearning_5params_k.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fourParamFixed'
        scriptName = ['stan_qLearning_4params_fixedParams_' ...
            p.Results.paramNames{setdiff([1:4], paramInds)} '.stan'];
        fit = stan('file',[filePath scriptName],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fourParamO'
        fit = stan('file',[filePath 'stan_qLearning_4params_opponency.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fiveParamO'
        fit = stan('file',[filePath 'stan_qLearning_5params_opponency.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParamO_rBarStart'
        fit = stan('file',[filePath 'stan_qLearning_6params_opponency_rBarStart.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fiveParamO_peUpdate'
        fit = stan('file',[filePath 'stan_qLearning_5params_opponency_peUpdate.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);    
    case 'sixParamO_rBarStart_peUpdate'
        fit = stan('file',[filePath 'stan_qLearning_6params_opponency_rBarStart_peUpdate.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath); 
    case 'fiveParam_peBeta'
        fit = stan('file',[filePath 'stan_qLearning_5params_peBeta.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fiveParam_peBeta_avg'
        fit = stan('file',[filePath 'stan_qLearning_5params_peBeta_avg.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fiveParam_peBeta_fixedMax'
        fit = stan('file',[filePath 'stan_qLearning_5params_peBeta_fixedMax.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_peBeta'
        fit = stan('file',[filePath 'stan_qLearning_6params_peBeta.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_pePeBeta'
        fit = stan('file',[filePath 'stan_qLearning_6params_pePeBeta.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_peBeta_diff'
        fit = stan('file',[filePath 'stan_qLearning_6params_peBeta_diff.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_absPePeBeta'
        fit = stan('file',[filePath 'stan_qLearning_6params_absPePeBeta.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_peBeta_k'
        fit = stan('file',[filePath 'stan_qLearning_7params_peBeta_k.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fourParam_rBeta_scale'
        fit = stan('file',[filePath 'stan_qLearning_4params_rBeta_scale.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fourParam_rBeta_confQ'
        fit = stan('file',[filePath 'stan_qLearning_4params_rBeta_confQ.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fiveParam_rBeta_confQ'
        fit = stan('file',[filePath 'stan_qLearning_5params_rBeta_confQ.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fiveParam_rBeta_scale'
        fit = stan('file',[filePath 'stan_qLearning_5params_rBeta_scale.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_rBeta_scale'
        fit = stan('file',[filePath 'stan_qLearning_6params_rBeta_scale.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath );
    case 'sixParam_rBeta_scale_min'
        fit = stan('file',[filePath 'stan_qLearning_6params_rBeta_scale_min.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath );
    case 'sixParam_rBeta_scale_max'
        fit = stan('file',[filePath 'stan_qLearning_6params_rBeta_scale_max.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath );
    case 'sixParam_rBeta_scale_initR'
        fit = stan('file',[filePath 'stan_qLearning_6params_rBeta_scale_initR.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath );
    case 'sixParam_rBeta_scale_kappa'
        fit = stan('file',[filePath 'stan_qLearning_6params_rBeta_scale_kappa.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath );
    case 'sixParam_rBeta_rRPE'
        fit = stan('file',[filePath 'stan_qLearning_6params_rBeta_rRPE.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_rBeta_rRPE_noMin'
        fit = stan('file',[filePath 'stan_qLearning_6params_rBeta_rRPE_noMin.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_rBeta_rV'
        fit = stan('file',[filePath 'stan_qLearning_6params_rBeta_rV.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fourParam_pePeAN_noScale'
        fit = stan('file',[filePath 'stan_qLearning_4params_pePeAN_noScale.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath); 
    case 'fiveParam_pePeAN_noScale'
        fit = stan('file',[filePath 'stan_qLearning_5params_pePeAN_noScale.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath); 
    case 'sixParam_peAN'
        fit = stan('file',[filePath 'stan_qLearning_6params_peAN.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_pePeAN'
        fit = stan('file',[filePath 'stan_qLearning_6params_pePeAN.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_pePeAN_bi'
        fit = stan('file',[filePath 'stan_qLearning_6params_pePeAN_bi.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fiveParam_pePeAN_lag'
        fit = stan('file',[filePath 'stan_qLearning_5params_pePeAN_lag.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_pePeAN_lag'
        fit = stan('file',[filePath 'stan_qLearning_6params_pePeAN_lag.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'fiveParam_absPePeAN'
        fit = stan('file',[filePath 'stan_qLearning_5params_absPePeAN.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath); 
    case 'sixParam_absPePeAN'
        fit = stan('file',[filePath 'stan_qLearning_6params_absPePeAN.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_absPePeAN_bi_bias'
        fit = stan('file',[filePath 'stan_qLearning_6params_absPePeAN_bi_bias.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_absPePeAN_bi'
        fit = stan('file',[filePath 'stan_qLearning_6params_absPePeAN_bi.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_absPePeAN_bi_bias'
        fit = stan('file',[filePath 'stan_qLearning_7params_absPePeAN_bi_bias.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_absPePeAN_bi_bias_bothF'
        fit = stan('file',[filePath 'stan_qLearning_7params_absPePeAN_bi_bias_bothF.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'eightParam_absPePeAN_bi_int_bias'
        fit = stan('file',[filePath 'stan_qLearning_8params_absPePeAN_bi_int_bias.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_absPePeAN_biSep'
        fit = stan('file',[filePath 'stan_qLearning_6params_absPePeAN_biSep.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_absPePeAN_biSep_f'
        fit = stan('file',[filePath 'stan_qLearning_7params_absPePeAN_biSep_f.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_absPePeAN_bi_k'
        fit = stan('file',[filePath 'stan_qLearning_7params_absPePeAN_bi_k.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'eightParam_absPePeAN_bi_bias_k'
        fit = stan('file',[filePath 'stan_qLearning_8params_absPePeAN_bi_bias_k.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_absPePeAN_exp'
        fit = stan('file',[filePath 'stan_qLearning_6params_absPePeAN_exp.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_absPePeAN_exp_bias'
        fit = stan('file',[filePath 'stan_qLearning_6params_absPePeAN_exp_bias.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_absPePeAN_exp_bias'
        fit = stan('file',[filePath 'stan_qLearning_7params_absPePeAN_exp_bias.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'eightParam_absPePeAN_exp_bias_k'
        fit = stan('file',[filePath 'stan_qLearning_8params_absPePeAN_exp_bias_k.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_absPePeAN_log'
        fit = stan('file',[filePath 'stan_qLearning_6params_absPePeAN_log.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_absPePeAN_log'
        fit = stan('file',[filePath 'stan_qLearning_7params_absPePeAN_log.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'eightParam_absPePeAN_thresh_bias'
        fit = stan('file',[filePath 'stan_qLearning_8params_absPePeAN_thresh_bias.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath); 
    case 'sevenParam_absPePeLR'
        fit = stan('file',[filePath 'stan_qLearning_7params_absPePeLR.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_pePeAN_k'
        fit = stan('file',[filePath 'stan_qLearning_7params_pePeAN_k.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_peLR'
        fit = stan('file',[filePath 'stan_qLearning_7params_peLR.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_pePeLR'
        fit = stan('file',[filePath 'stan_qLearning_7params_pePeLR.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'eightParam_absPePeLR_k'
        fit = stan('file',[filePath 'stan_qLearning_8params_absPePeLR_k.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_rAN'
        fit = stan('file',[filePath 'stan_qLearning_6params_rAN.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_rBeta_oppo'
        fit = stan('file',[filePath 'stan_qLearning_6params_rBeta_oppo.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sevenParam_rBeta_oppo_rStart'
        fit = stan('file',[filePath 'stan_qLearning_7params_rBeta_oppo_rStart.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'sixParam_rBeta_oppo_rCont'
        fit = stan('file',[filePath 'stan_qLearning_6params_rBeta_oppo_rCont.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'eightParam_rBeta_pePeAN'
        fit = stan('file',[filePath 'stan_qLearning_8params_rBeta_pePeAN.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'eightParam_rBeta_absPePeAN'
        fit = stan('file',[filePath 'stan_qLearning_8params_rBeta_absPePeAN.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    case 'tenParam_rBeta_pePeAN_kb'
        fit = stan('file',[filePath 'stan_qLearning_10params_rBeta_pePeAN_kb.stan'],'data',session_dat,'verbose', true,...
            'iter', iter, 'warmup', warmup, 'working_dir', savePath);
    otherwise
        error([p.Results.modelName ' does not exist'])
end
