function [t, allRewards, allChoices, blockProbs, blockSwitch] = runSim_dF(modelName, params, maxTrials, rSeed, rwdProbs, varargin)


a = inputParser;
% default parameters if none given
a.addParameter('taskType', 'decoupled')
a.addParameter('blockLength', [20 35])
a.parse(varargin{:});

switch modelName
    case 'threeParam_bias'
        [t,allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'fourParam'
        [t,allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'fiveParam_k'
        [allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_k_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'fiveParamO'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_oppo_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'fiveParam_rBeta_scale'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_rBeta_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'fiveParam_rBeta_kappa'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_rBetaKappa_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParamO_rBarStart'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_oppo_rBarStart_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_rBeta_oppo'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_rBeta_oppo_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_peBeta'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_peBeta_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_peBeta_k'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_peBeta_k_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_pePeBeta'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_pePeBeta_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_rAN'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_rAN_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_peAN'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_peAN_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_pePeAN'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_pePeAN_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_pePeAN_bi'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_pePeAN_bi_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_pePeAN_lag'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_pePeAN_lag_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePeAN'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePeAN_bi'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_bi_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePeAN_bi_tW'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_bi_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePeAN_bi_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_bi_bias_noEps_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePeAN_bi_bias_noF'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_bi_bias_noF_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_bi_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_bi_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_bi_bias_bothF'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_bi_bias_bothF_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'eightParam_absPePeAN_bi_int_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_bi_int_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_bi_bias_tW'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_bi_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePeAN_biSep'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_biSep_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_biSep_f'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_biSep_f_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_bi_k'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_bi_k_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'eightParam_absPePeAN_bi_bias_k'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_bi_bias_k_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'fiveParam_absPePeAN'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_noMin_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePeAN_exp'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_exp_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePeAN_exp_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_exp_bias_noF_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_exp_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_exp_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'eightParam_absPePeAN_exp_bias_k'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_exp_bias_k_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_exp_bias_tW'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_exp_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePeAN_exp_tW'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_exp_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePeAN_log'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_log_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_log'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_log3_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'eightParam_absPePeAN_thresh_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_thresh_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePe_scale_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePe_scale_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength); 
    case 'sixParam_absPePe_scale_bias_tight'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePe_scale_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePe_scaleSep_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePe_scaleSep_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_absPePe_scaleBoth_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePe_scaleBoth_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_scale_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_scale_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength); 
    case 'eightParam_absPePeAN_int_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_int_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'eightParam_absPePeAN_scale_int_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_scale_int_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeLR'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeLR_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'eightParam_absPePeLR_k'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeLR_k_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_pePeAN_k'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_pePeAN_k_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_peLR'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_peLR_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'eightParam_rBeta_pePeAN'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_rBeta_pePeAN_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'eightParam_rBeta_absPePeAN'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_rBeta_absPePeAN_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);

%% most recent
    case 'fiveParam_bias'
        [t,allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'fiveParam_ph_bias'
        [t,allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_ph_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sixParam_ph_bias'
        [t,allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_ph_2LR_bias_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_int_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_int_bias_noEps_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength); 
    case 'sevenParam_absPePeAN_int_bias_ord'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_int_bias_noEps_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength); 
    case 'sevenParam_absPePeAN_scale_int_bias'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_scale_int_bias_noEps_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_absPePeAN_scale_int_bias_ord'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_absPePeAN_scale_int_bias_noEps_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
        
    case 'sixParam_rTrace'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_rTrace_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'sevenParam_rTrace_k'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = qLearningModel_rTrace_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'twoParam_wsls'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = wsls_simNoPlot('params', params,...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'taskType', a.Results.taskType, 'blockLength', a.Results.blockLength);
    case 'vkf'
        [t, allRewards, allChoices, blockProbs, blockSwitch] = vkfSim('params', params, ...
            'maxTrials', maxTrials, 'randomSeed', rSeed, 'rwdProbs', rwdProbs, 'blockLength', a.Results.blockLength);
end

end
