
// Code generated by stanc f556d0df
#include <stan/model/model_header.hpp>
namespace gcampTest_model_namespace {

template <typename T, typename S>
std::vector<T> resize_to_match__(std::vector<T>& dst, const std::vector<S>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, -1>
resize_to_match__(Eigen::Matrix<T, -1, -1>& dst, const Eigen::Matrix<T, -1, -1>& src) {
  dst.resize(src.rows(), src.cols());
  return dst;
}

template <typename T>
Eigen::Matrix<T, 1, -1>
resize_to_match__(Eigen::Matrix<T, 1, -1>& dst, const Eigen::Matrix<T, 1, -1>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, 1>
resize_to_match__(Eigen::Matrix<T, -1, 1>& dst, const Eigen::Matrix<T, -1, 1>& src) {
  dst.resize(src.size());
  return dst;
}
std::vector<double> to_doubles__(std::initializer_list<double> x) {
  return x;
}

std::vector<stan::math::var> to_vars__(std::initializer_list<stan::math::var> x) {
  return x;
}

inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math; 

static int current_statement__ = 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 9, column 2 to column 25)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 10, column 2 to column 24)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 11, column 2 to column 14)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 12, column 2 to column 15)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 15, column 2 to column 24)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 16, column 2 to column 25)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 17, column 2 to column 29)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 19, column 2 to column 27)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 20, column 2 to column 28)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 24, column 2 to column 40)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 25, column 2 to column 22)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 26, column 2 to column 26)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 28, column 2 to column 57)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 29, column 2 to column 59)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 30, column 2 to column 43)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 34, column 2 to column 23)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 35, column 2 to column 22)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 36, column 2 to column 30)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 38, column 2 to column 24)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 39, column 2 to column 25)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 41, column 2 to column 25)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 42, column 2 to column 26)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 44, column 2 to column 28)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 45, column 2 to column 29)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 49, column 4 to column 29)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 50, column 4 to column 33)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 51, column 4 to column 36)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 53, column 4 to column 36)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 54, column 4 to column 42)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 56, column 4 to column 47)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 57, column 4 to column 38)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 59, column 4 to column 39)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 48, column 17 to line 60, column 3)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 48, column 2 to line 60, column 3)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 2, column 2 to column 17)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 3, column 2 to column 17)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 4, column 2 to column 33)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 5, column 2 to column 22)",
                                                      " (in 'C:/Users/zhixi/Documents/gitRepositories/sueAnalysis/matlabCode/operantMatching/learningModels/stan/GCaMP/gcampTest.stan', line 6, column 2 to column 25)"};



class gcampTest_model : public model_base_crtp<gcampTest_model> {

 private:
  int pos__;
  int N;
  int T;
  std::vector<int> Tsesh;
  Eigen::Matrix<double, -1, -1> rpeMat;
  Eigen::Matrix<double, -1, -1> signalMat;
 
 public:
  ~gcampTest_model() { }
  
  std::string model_name() const { return "gcampTest_model"; }
  
  gcampTest_model(stan::io::var_context& context__,
                  unsigned int random_seed__ = 0,
                  std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    typedef double local_scalar_t__;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "gcampTest_model_namespace::gcampTest_model";
    (void) function__;  // suppress unused var warning
    
    try {
      
      pos__ = 1;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      
      current_statement__ = 35;
      N = context__.vals_i("N")[(1 - 1)];
      context__.validate_dims("data initialization","T","int",
          context__.to_vec());
      
      current_statement__ = 36;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 37;
      validate_non_negative_index("Tsesh", "N", N);
      context__.validate_dims("data initialization","Tsesh","int",
          context__.to_vec(N));
      Tsesh = std::vector<int>(N, 0);
      
      current_statement__ = 37;
      assign(Tsesh, nil_index_list(), context__.vals_i("Tsesh"),
        "assigning variable Tsesh");
      current_statement__ = 38;
      validate_non_negative_index("rpeMat", "N", N);
      current_statement__ = 38;
      validate_non_negative_index("rpeMat", "T", T);
      context__.validate_dims("data initialization","rpeMat","double",
          context__.to_vec(N, T));
      rpeMat = Eigen::Matrix<double, -1, -1>(N, T);
      
      {
        std::vector<local_scalar_t__> rpeMat_flat__;
        current_statement__ = 38;
        assign(rpeMat_flat__, nil_index_list(), context__.vals_r("rpeMat"),
          "assigning variable rpeMat_flat__");
        current_statement__ = 38;
        pos__ = 1;
        current_statement__ = 38;
        for (size_t sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 38;
          for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 38;
            assign(rpeMat,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              rpeMat_flat__[(pos__ - 1)], "assigning variable rpeMat");
            current_statement__ = 38;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 39;
      validate_non_negative_index("signalMat", "N", N);
      current_statement__ = 39;
      validate_non_negative_index("signalMat", "T", T);
      context__.validate_dims("data initialization","signalMat","double",
          context__.to_vec(N, T));
      signalMat = Eigen::Matrix<double, -1, -1>(N, T);
      
      {
        std::vector<local_scalar_t__> signalMat_flat__;
        current_statement__ = 39;
        assign(signalMat_flat__, nil_index_list(),
          context__.vals_r("signalMat"),
          "assigning variable signalMat_flat__");
        current_statement__ = 39;
        pos__ = 1;
        current_statement__ = 39;
        for (size_t sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 39;
          for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 39;
            assign(signalMat,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              signalMat_flat__[(pos__ - 1)], "assigning variable signalMat");
            current_statement__ = 39;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 35;
      current_statement__ = 35;
      check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 36;
      current_statement__ = 36;
      check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 37;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 37;
        current_statement__ = 37;
        check_greater_or_equal(function__, "Tsesh[sym1__]",
                               Tsesh[(sym1__ - 1)], 1);}
      current_statement__ = 37;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 37;
        current_statement__ = 37;
        check_less_or_equal(function__, "Tsesh[sym1__]", Tsesh[(sym1__ - 1)],
                            T);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      current_statement__ = 1;
      validate_non_negative_index("sigma", "N", N);
      num_params_r__ += N;
      current_statement__ = 2;
      validate_non_negative_index("maxF", "N", N);
      num_params_r__ += N;
      num_params_r__ += 1;
      num_params_r__ += 1;
      current_statement__ = 5;
      validate_non_negative_index("half_pr", "N", N);
      num_params_r__ += N;
      current_statement__ = 6;
      validate_non_negative_index("slope_pr", "N", N);
      num_params_r__ += N;
      current_statement__ = 7;
      validate_non_negative_index("intercept_pr", "N", N);
      num_params_r__ += N;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename T__>
  T__ log_prob(std::vector<T__>& params_r__, std::vector<int>& params_i__,
               std::ostream* pstream__ = 0) const {
    typedef T__ local_scalar_t__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "gcampTest_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    
    try {
      current_statement__ = 1;
      validate_non_negative_index("sigma", "N", N);
      std::vector<local_scalar_t__> sigma;
      sigma = std::vector<local_scalar_t__>(N, 0);
      
      current_statement__ = 1;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable sigma");}
      current_statement__ = 1;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        if (jacobian__) {
          current_statement__ = 1;
          assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(sigma[(sym1__ - 1)], 0, lp__),
            "assigning variable sigma");
        } else {
          current_statement__ = 1;
          assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(sigma[(sym1__ - 1)], 0),
            "assigning variable sigma");
        }}
      current_statement__ = 2;
      validate_non_negative_index("maxF", "N", N);
      std::vector<local_scalar_t__> maxF;
      maxF = std::vector<local_scalar_t__>(N, 0);
      
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        assign(maxF, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable maxF");}
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        if (jacobian__) {
          current_statement__ = 2;
          assign(maxF, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(maxF[(sym1__ - 1)], 0, lp__),
            "assigning variable maxF");
        } else {
          current_statement__ = 2;
          assign(maxF, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(maxF[(sym1__ - 1)], 0),
            "assigning variable maxF");
        }}
      local_scalar_t__ half_a;
      
      current_statement__ = 3;
      half_a = in__.scalar();
      local_scalar_t__ slope_a;
      
      current_statement__ = 4;
      slope_a = in__.scalar();
      current_statement__ = 5;
      validate_non_negative_index("half_pr", "N", N);
      Eigen::Matrix<local_scalar_t__, 1, -1> half_pr;
      half_pr = Eigen::Matrix<local_scalar_t__, 1, -1>(N);
      
      current_statement__ = 5;
      half_pr = in__.row_vector(N);
      current_statement__ = 6;
      validate_non_negative_index("slope_pr", "N", N);
      Eigen::Matrix<local_scalar_t__, 1, -1> slope_pr;
      slope_pr = Eigen::Matrix<local_scalar_t__, 1, -1>(N);
      
      current_statement__ = 6;
      slope_pr = in__.row_vector(N);
      current_statement__ = 7;
      validate_non_negative_index("intercept_pr", "N", N);
      Eigen::Matrix<local_scalar_t__, 1, -1> intercept_pr;
      intercept_pr = Eigen::Matrix<local_scalar_t__, 1, -1>(N);
      
      current_statement__ = 7;
      intercept_pr = in__.row_vector(N);
      local_scalar_t__ sigma_half;
      
      current_statement__ = 8;
      sigma_half = in__.scalar();
      current_statement__ = 8;
      if (jacobian__) {
        current_statement__ = 8;
        sigma_half = stan::math::lb_constrain(sigma_half, 0, lp__);
      } else {
        current_statement__ = 8;
        sigma_half = stan::math::lb_constrain(sigma_half, 0);
      }
      local_scalar_t__ sigma_slope;
      
      current_statement__ = 9;
      sigma_slope = in__.scalar();
      current_statement__ = 9;
      if (jacobian__) {
        current_statement__ = 9;
        sigma_slope = stan::math::lb_constrain(sigma_slope, 0, lp__);
      } else {
        current_statement__ = 9;
        sigma_slope = stan::math::lb_constrain(sigma_slope, 0);
      }
      current_statement__ = 10;
      validate_non_negative_index("half", "N", N);
      Eigen::Matrix<local_scalar_t__, 1, -1> half;
      half = Eigen::Matrix<local_scalar_t__, 1, -1>(N);
      
      current_statement__ = 10;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 10;
        assign(half, cons_list(index_uni(sym1__), nil_index_list()),
          std::numeric_limits<double>::quiet_NaN(), "assigning variable half");
      }
      current_statement__ = 11;
      validate_non_negative_index("slope", "N", N);
      Eigen::Matrix<local_scalar_t__, 1, -1> slope;
      slope = Eigen::Matrix<local_scalar_t__, 1, -1>(N);
      
      current_statement__ = 11;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 11;
        assign(slope, cons_list(index_uni(sym1__), nil_index_list()),
          std::numeric_limits<double>::quiet_NaN(),
          "assigning variable slope");}
      current_statement__ = 12;
      validate_non_negative_index("intercept", "N", N);
      Eigen::Matrix<local_scalar_t__, 1, -1> intercept;
      intercept = Eigen::Matrix<local_scalar_t__, 1, -1>(N);
      
      current_statement__ = 12;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 12;
        assign(intercept, cons_list(index_uni(sym1__), nil_index_list()),
          std::numeric_limits<double>::quiet_NaN(),
          "assigning variable intercept");}
      current_statement__ = 13;
      assign(half, nil_index_list(),
        subtract(
          multiply(2, Phi_approx(add(half_a, multiply(half_pr, sigma_half)))),
          1), "assigning variable half");
      current_statement__ = 14;
      assign(slope, nil_index_list(),
        multiply(4,
          Phi_approx(add(slope_a, multiply(slope_pr, sigma_slope)))),
        "assigning variable slope");
      current_statement__ = 15;
      assign(intercept, nil_index_list(),
        multiply(2, Phi_approx(intercept_pr)), "assigning variable intercept");
      current_statement__ = 10;
      current_statement__ = 10;
      check_greater_or_equal(function__, "half", half, -2);
      current_statement__ = 10;
      current_statement__ = 10;
      check_less_or_equal(function__, "half", half, 2);
      {
        current_statement__ = 16;
        lp_accum__.add(cauchy_log<propto__>(sigma, 0, 1));
        current_statement__ = 17;
        lp_accum__.add(normal_log<propto__>(maxF, 0, 1));
        current_statement__ = 18;
        lp_accum__.add(normal_log<propto__>(intercept_pr, 0, 1));
        current_statement__ = 19;
        lp_accum__.add(normal_log<propto__>(half_a, 0, 1));
        current_statement__ = 20;
        lp_accum__.add(normal_log<propto__>(slope_a, 0, 1));
        current_statement__ = 21;
        lp_accum__.add(normal_log<propto__>(half_pr, 0, 1));
        current_statement__ = 22;
        lp_accum__.add(normal_log<propto__>(slope_pr, 0, 1));
        current_statement__ = 23;
        lp_accum__.add(cauchy_log<propto__>(sigma_half, 0, 1));
        current_statement__ = 24;
        lp_accum__.add(cauchy_log<propto__>(sigma_slope, 0, 1));
        current_statement__ = 34;
        for (size_t n = 1; n <= N; ++n) {
          current_statement__ = 25;
          validate_non_negative_index("est", "Tsesh[(n - 1)]", Tsesh[(n - 1)]);
          Eigen::Matrix<local_scalar_t__, 1, -1> est;
          est = Eigen::Matrix<local_scalar_t__, 1, -1>(Tsesh[(n - 1)]);
          
          current_statement__ = 25;
          for (size_t sym1__ = 1; sym1__ <= Tsesh[(n - 1)]; ++sym1__) {
            current_statement__ = 25;
            assign(est, cons_list(index_uni(sym1__), nil_index_list()),
              std::numeric_limits<double>::quiet_NaN(),
              "assigning variable est");}
          current_statement__ = 26;
          validate_non_negative_index("currRpe", "Tsesh[(n - 1)]",
                                      Tsesh[(n - 1)]);
          Eigen::Matrix<local_scalar_t__, 1, -1> currRpe;
          currRpe = Eigen::Matrix<local_scalar_t__, 1, -1>(Tsesh[(n - 1)]);
          
          current_statement__ = 26;
          for (size_t sym1__ = 1; sym1__ <= Tsesh[(n - 1)]; ++sym1__) {
            current_statement__ = 26;
            assign(currRpe, cons_list(index_uni(sym1__), nil_index_list()),
              std::numeric_limits<double>::quiet_NaN(),
              "assigning variable currRpe");}
          current_statement__ = 27;
          validate_non_negative_index("currSignal", "Tsesh[(n - 1)]",
                                      Tsesh[(n - 1)]);
          Eigen::Matrix<local_scalar_t__, 1, -1> currSignal;
          currSignal = Eigen::Matrix<local_scalar_t__, 1, -1>(Tsesh[(n - 1)]);
          
          current_statement__ = 27;
          for (size_t sym1__ = 1; sym1__ <= Tsesh[(n - 1)]; ++sym1__) {
            current_statement__ = 27;
            assign(currSignal,
              cons_list(index_uni(sym1__), nil_index_list()),
              std::numeric_limits<double>::quiet_NaN(),
              "assigning variable currSignal");}
          current_statement__ = 28;
          assign(currRpe, nil_index_list(),
            rvalue(rpeMat,
              cons_list(index_uni(n),
                cons_list(index_min_max(1, Tsesh[(n - 1)]), nil_index_list())),
              "rpeMat"), "assigning variable currRpe");
          current_statement__ = 29;
          assign(currSignal, nil_index_list(),
            rvalue(signalMat,
              cons_list(index_uni(n),
                cons_list(index_min_max(1, Tsesh[(n - 1)]), nil_index_list())),
              "signalMat"), "assigning variable currSignal");
          current_statement__ = 30;
          assign(est, nil_index_list(),
            add(1,
              stan::math::exp(
                multiply(-slope[(n - 1)], subtract(currRpe, half[(n - 1)])))),
            "assigning variable est");
          current_statement__ = 31;
          assign(est, nil_index_list(),
            add(elt_divide(maxF[(n - 1)], stan::model::deep_copy(est)),
              intercept[(n - 1)]), "assigning variable est");
          current_statement__ = 32;
          lp_accum__.add(
            normal_log<propto__>(currSignal, est, sigma[(n - 1)]));}
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob() 
    
  template <typename RNG>
  void write_array(RNG& base_rng__, std::vector<double>& params_r__,
                   std::vector<int>& params_i__, std::vector<double>& vars__,
                   bool emit_transformed_parameters__ = true,
                   bool emit_generated_quantities__ = true,
                   std::ostream* pstream__ = 0) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "gcampTest_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    
    try {
      current_statement__ = 1;
      validate_non_negative_index("sigma", "N", N);
      std::vector<double> sigma;
      sigma = std::vector<double>(N, 0);
      
      current_statement__ = 1;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable sigma");}
      current_statement__ = 1;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(sigma[(sym1__ - 1)], 0),
          "assigning variable sigma");}
      current_statement__ = 2;
      validate_non_negative_index("maxF", "N", N);
      std::vector<double> maxF;
      maxF = std::vector<double>(N, 0);
      
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        assign(maxF, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable maxF");}
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        assign(maxF, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(maxF[(sym1__ - 1)], 0),
          "assigning variable maxF");}
      double half_a;
      
      current_statement__ = 3;
      half_a = in__.scalar();
      double slope_a;
      
      current_statement__ = 4;
      slope_a = in__.scalar();
      current_statement__ = 5;
      validate_non_negative_index("half_pr", "N", N);
      Eigen::Matrix<double, 1, -1> half_pr;
      half_pr = Eigen::Matrix<double, 1, -1>(N);
      
      current_statement__ = 5;
      half_pr = in__.row_vector(N);
      current_statement__ = 6;
      validate_non_negative_index("slope_pr", "N", N);
      Eigen::Matrix<double, 1, -1> slope_pr;
      slope_pr = Eigen::Matrix<double, 1, -1>(N);
      
      current_statement__ = 6;
      slope_pr = in__.row_vector(N);
      current_statement__ = 7;
      validate_non_negative_index("intercept_pr", "N", N);
      Eigen::Matrix<double, 1, -1> intercept_pr;
      intercept_pr = Eigen::Matrix<double, 1, -1>(N);
      
      current_statement__ = 7;
      intercept_pr = in__.row_vector(N);
      double sigma_half;
      
      current_statement__ = 8;
      sigma_half = in__.scalar();
      current_statement__ = 8;
      sigma_half = stan::math::lb_constrain(sigma_half, 0);
      double sigma_slope;
      
      current_statement__ = 9;
      sigma_slope = in__.scalar();
      current_statement__ = 9;
      sigma_slope = stan::math::lb_constrain(sigma_slope, 0);
      current_statement__ = 10;
      validate_non_negative_index("half", "N", N);
      Eigen::Matrix<double, 1, -1> half;
      half = Eigen::Matrix<double, 1, -1>(N);
      
      current_statement__ = 10;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 10;
        assign(half, cons_list(index_uni(sym1__), nil_index_list()),
          std::numeric_limits<double>::quiet_NaN(), "assigning variable half");
      }
      current_statement__ = 11;
      validate_non_negative_index("slope", "N", N);
      Eigen::Matrix<double, 1, -1> slope;
      slope = Eigen::Matrix<double, 1, -1>(N);
      
      current_statement__ = 11;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 11;
        assign(slope, cons_list(index_uni(sym1__), nil_index_list()),
          std::numeric_limits<double>::quiet_NaN(),
          "assigning variable slope");}
      current_statement__ = 12;
      validate_non_negative_index("intercept", "N", N);
      Eigen::Matrix<double, 1, -1> intercept;
      intercept = Eigen::Matrix<double, 1, -1>(N);
      
      current_statement__ = 12;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 12;
        assign(intercept, cons_list(index_uni(sym1__), nil_index_list()),
          std::numeric_limits<double>::quiet_NaN(),
          "assigning variable intercept");}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(sigma[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(maxF[(sym1__ - 1)]);}
      vars__.push_back(half_a);
      vars__.push_back(slope_a);
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(half_pr[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(slope_pr[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(intercept_pr[(sym1__ - 1)]);}
      vars__.push_back(sigma_half);
      vars__.push_back(sigma_slope);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 13;
      assign(half, nil_index_list(),
        subtract(
          multiply(2, Phi_approx(add(half_a, multiply(half_pr, sigma_half)))),
          1), "assigning variable half");
      current_statement__ = 14;
      assign(slope, nil_index_list(),
        multiply(4,
          Phi_approx(add(slope_a, multiply(slope_pr, sigma_slope)))),
        "assigning variable slope");
      current_statement__ = 15;
      assign(intercept, nil_index_list(),
        multiply(2, Phi_approx(intercept_pr)), "assigning variable intercept");
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(half[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(slope[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(intercept[(sym1__ - 1)]);}
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array() 
    
  void transform_inits(const stan::io::var_context& context__,
                       std::vector<int>& params_i__,
                       std::vector<double>& vars__, std::ostream* pstream__) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      
      pos__ = 1;
      current_statement__ = 1;
      validate_non_negative_index("sigma", "N", N);
      std::vector<double> sigma;
      sigma = std::vector<double>(N, 0);
      
      current_statement__ = 1;
      assign(sigma, nil_index_list(), context__.vals_r("sigma"),
        "assigning variable sigma");
      current_statement__ = 1;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(sigma[(sym1__ - 1)], 0),
          "assigning variable sigma");}
      current_statement__ = 2;
      validate_non_negative_index("maxF", "N", N);
      std::vector<double> maxF;
      maxF = std::vector<double>(N, 0);
      
      current_statement__ = 2;
      assign(maxF, nil_index_list(), context__.vals_r("maxF"),
        "assigning variable maxF");
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        assign(maxF, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(maxF[(sym1__ - 1)], 0),
          "assigning variable maxF");}
      double half_a;
      
      current_statement__ = 3;
      half_a = context__.vals_r("half_a")[(1 - 1)];
      double slope_a;
      
      current_statement__ = 4;
      slope_a = context__.vals_r("slope_a")[(1 - 1)];
      current_statement__ = 5;
      validate_non_negative_index("half_pr", "N", N);
      Eigen::Matrix<double, 1, -1> half_pr;
      half_pr = Eigen::Matrix<double, 1, -1>(N);
      
      {
        std::vector<local_scalar_t__> half_pr_flat__;
        current_statement__ = 5;
        assign(half_pr_flat__, nil_index_list(), context__.vals_r("half_pr"),
          "assigning variable half_pr_flat__");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 5;
          assign(half_pr, cons_list(index_uni(sym1__), nil_index_list()),
            half_pr_flat__[(pos__ - 1)], "assigning variable half_pr");
          current_statement__ = 5;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 6;
      validate_non_negative_index("slope_pr", "N", N);
      Eigen::Matrix<double, 1, -1> slope_pr;
      slope_pr = Eigen::Matrix<double, 1, -1>(N);
      
      {
        std::vector<local_scalar_t__> slope_pr_flat__;
        current_statement__ = 6;
        assign(slope_pr_flat__, nil_index_list(),
          context__.vals_r("slope_pr"), "assigning variable slope_pr_flat__");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 6;
          assign(slope_pr, cons_list(index_uni(sym1__), nil_index_list()),
            slope_pr_flat__[(pos__ - 1)], "assigning variable slope_pr");
          current_statement__ = 6;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 7;
      validate_non_negative_index("intercept_pr", "N", N);
      Eigen::Matrix<double, 1, -1> intercept_pr;
      intercept_pr = Eigen::Matrix<double, 1, -1>(N);
      
      {
        std::vector<local_scalar_t__> intercept_pr_flat__;
        current_statement__ = 7;
        assign(intercept_pr_flat__, nil_index_list(),
          context__.vals_r("intercept_pr"),
          "assigning variable intercept_pr_flat__");
        current_statement__ = 7;
        pos__ = 1;
        current_statement__ = 7;
        for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 7;
          assign(intercept_pr,
            cons_list(index_uni(sym1__), nil_index_list()),
            intercept_pr_flat__[(pos__ - 1)],
            "assigning variable intercept_pr");
          current_statement__ = 7;
          pos__ = (pos__ + 1);}
      }
      double sigma_half;
      
      current_statement__ = 8;
      sigma_half = context__.vals_r("sigma_half")[(1 - 1)];
      current_statement__ = 8;
      sigma_half = stan::math::lb_free(sigma_half, 0);
      double sigma_slope;
      
      current_statement__ = 9;
      sigma_slope = context__.vals_r("sigma_slope")[(1 - 1)];
      current_statement__ = 9;
      sigma_slope = stan::math::lb_free(sigma_slope, 0);
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(sigma[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(maxF[(sym1__ - 1)]);}
      vars__.push_back(half_a);
      vars__.push_back(slope_a);
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(half_pr[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(slope_pr[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(intercept_pr[(sym1__ - 1)]);}
      vars__.push_back(sigma_half);
      vars__.push_back(sigma_slope);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits() 
    
  void get_param_names(std::vector<std::string>& names__) const {
    
    names__.resize(0);
    names__.push_back("sigma");
    names__.push_back("maxF");
    names__.push_back("half_a");
    names__.push_back("slope_a");
    names__.push_back("half_pr");
    names__.push_back("slope_pr");
    names__.push_back("intercept_pr");
    names__.push_back("sigma_half");
    names__.push_back("sigma_slope");
    names__.push_back("half");
    names__.push_back("slope");
    names__.push_back("intercept");
    } // get_param_names() 
    
  void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.resize(0);
    std::vector<size_t> dims__;
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    
    } // get_dims() 
    
  void constrained_param_names(std::vector<std::string>& param_names__,
                               bool emit_transformed_parameters__ = true,
                               bool emit_generated_quantities__ = true) const {
    
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "sigma" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "maxF" + '.' + std::to_string(sym1__));
      }}
    param_names__.push_back(std::string() + "half_a");
    param_names__.push_back(std::string() + "slope_a");
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "half_pr" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "slope_pr" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "intercept_pr" + '.' + std::to_string(sym1__));
      }}
    param_names__.push_back(std::string() + "sigma_half");
    param_names__.push_back(std::string() + "sigma_slope");
    if (emit_transformed_parameters__) {
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "half" + '.' + std::to_string(sym1__));
        }}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "slope" + '.' + std::to_string(sym1__));
        }}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "intercept" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  void unconstrained_param_names(std::vector<std::string>& param_names__,
                                 bool emit_transformed_parameters__ = true,
                                 bool emit_generated_quantities__ = true) const {
    
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "sigma" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "maxF" + '.' + std::to_string(sym1__));
      }}
    param_names__.push_back(std::string() + "half_a");
    param_names__.push_back(std::string() + "slope_a");
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "half_pr" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "slope_pr" + '.' + std::to_string(sym1__));
      }}
    for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.push_back(std::string() + "intercept_pr" + '.' + std::to_string(sym1__));
      }}
    param_names__.push_back(std::string() + "sigma_half");
    param_names__.push_back(std::string() + "sigma_slope");
    if (emit_transformed_parameters__) {
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "half" + '.' + std::to_string(sym1__));
        }}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "slope" + '.' + std::to_string(sym1__));
        }}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "intercept" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"sigma\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"maxF\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"half_a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"slope_a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"half_pr\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"slope_pr\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"intercept_pr\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"sigma_half\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_slope\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"half\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"},{\"name\":\"slope\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"},{\"name\":\"intercept\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"sigma\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"maxF\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"half_a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"slope_a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"half_pr\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"slope_pr\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"intercept_pr\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"sigma_half\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_slope\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"half\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"},{\"name\":\"slope\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"},{\"name\":\"intercept\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool emit_transformed_parameters__ = true,
                     bool emit_generated_quantities__ = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng__, params_r_vec, params_i_vec, vars_vec,
          emit_transformed_parameters__, emit_generated_quantities__, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    template <bool propto__, bool jacobian__, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto__,jacobian__,T_>(vec_params_r, vec_params_i, pstream);
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }

};
}
typedef gcampTest_model_namespace::gcampTest_model stan_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


